from __future__ import annotations

from core.config import get_settings
from core.orchestrator import QAFactoryOrchestrator
from tools.code_executor import SafeCodeExecutor


def test_job_mode_generates_outputs(tmp_path, monkeypatch):
    monkeypatch.setenv("OUTPUT_DIR", str(tmp_path / "outputs"))
    settings = get_settings()
    state = QAFactoryOrchestrator(settings).run("job", "Need Playwright TypeScript QA automation for SaaS CI/CD.")
    assert state.stack_choice == "playwright-ts"
    assert "proposal.md" in state.generated_outputs
    assert "qa_plan.md" in state.generated_outputs
    assert "HUMAN_REVIEW_REQUIRED.md" in state.generated_outputs
    assert (tmp_path / "outputs" / state.project_id / "proposal.md").exists()


def test_scaffold_mode_generates_playwright_framework(tmp_path, monkeypatch):
    monkeypatch.setenv("OUTPUT_DIR", str(tmp_path / "outputs"))
    settings = get_settings()
    state = QAFactoryOrchestrator(settings).run("scaffold", "AI SaaS MVP with login, dashboard, API and GitHub Actions.")
    assert "framework/package.json" in state.generated_outputs
    assert "framework/playwright.config.ts" in state.generated_outputs
    assert "framework/pages/LoginPage.ts" in state.generated_outputs
    assert "framework/tests/ui/smoke.spec.ts" in state.generated_outputs
    assert "framework/tests/a11y/basic-a11y.spec.ts" in state.generated_outputs
    assert "TEST_RUNNER_NOTE.md" in state.generated_outputs
    assert (tmp_path / "outputs" / state.project_id / "framework" / "package.json").exists()


def test_full_mode_generates_internal_package(tmp_path, monkeypatch):
    monkeypatch.setenv("OUTPUT_DIR", str(tmp_path / "outputs"))
    settings = get_settings()
    state = QAFactoryOrchestrator(settings).run("full", "Upwork job: Playwright TypeScript QA audit for flaky tests, API checks and CI.")
    assert "proposal.md" in state.generated_outputs
    assert "framework/README.md" in state.generated_outputs
    assert "flakiness_review.md" in state.generated_outputs
    assert "delivery_note.md" in state.generated_outputs
    assert "PLAYWRIGHT_MCP_WORKFLOW.md" in state.generated_outputs


def test_safe_executor_blocks_non_allowlisted_command(tmp_path):
    result = SafeCodeExecutor().run(["rm", "-rf", "/"], cwd=tmp_path)
    assert result.success is False
    assert result.returncode == 126


def test_review_mode_bypasses_job_analysis(tmp_path, monkeypatch):
    monkeypatch.setenv("OUTPUT_DIR", str(tmp_path / "outputs"))
    settings = get_settings()
    state = QAFactoryOrchestrator(settings).run("review", "await page.waitForTimeout(5000);")
    assert "flakiness_review.md" in state.generated_outputs
    assert "analysis.md" not in state.generated_outputs


def test_generated_scaffold_uses_v508_and_npm_install(tmp_path, monkeypatch):
    monkeypatch.setenv("OUTPUT_DIR", str(tmp_path / "outputs"))
    settings = get_settings()
    state = QAFactoryOrchestrator(settings).run("scaffold", "Playwright TypeScript SaaS app")
    assert "Generated by AI QA Factory v5.0.8 Model Routing Profiles" in state.generated_outputs["framework/README.md"]
    workflow = state.generated_outputs["framework/.github/workflows/playwright.yml"]
    assert "npm install" in workflow
    assert "npm ci" not in workflow
