"""Current operator surfaces must describe the running product without stale release claims."""
from __future__ import annotations

from pathlib import Path

import pytest

import main as factory_main
from agents.playwright_generator import PlaywrightGeneratorAgent
from core.scout import SCOUT_VERSION
from core.state import QAFactoryState
from core.version import APP_VERSION
from tools.report_builder import ReportBuilder


def test_default_pytest_command_collects_only_the_test_suite():
    config = Path(__file__).resolve().parents[1] / "pytest.ini"
    assert "testpaths = tests" in config.read_text(encoding="utf-8")


def test_capabilities_is_cwd_independent_and_prints_runtime_identity(
    tmp_path, monkeypatch, capsys
):
    monkeypatch.chdir(tmp_path)
    assert factory_main.main(["capabilities"]) == 0
    output = capsys.readouterr().out
    assert f"AI QA Factory v{APP_VERSION}; Scout v{SCOUT_VERSION}" in output
    assert "runtime | conditional | generator/planning | not runtime" in output
    assert "Screenshot-only client-input understanding | not runtime" in output
    assert "Automatic reversible business interactions | not runtime" in output
    assert "Parallel Scout site execution | not runtime" in output


def test_help_uses_current_scout_version_and_current_concurrency_claim(capsys):
    with pytest.raises(SystemExit) as exc:
        factory_main.main(["--help"])
    assert exc.value.code == 0
    assert f"Prospect QA Scout v{SCOUT_VERSION}" in capsys.readouterr().out

    with pytest.raises(SystemExit) as exc:
        factory_main.main(["scout", "--help"])
    assert exc.value.code == 0
    output = capsys.readouterr().out
    assert f"Prospect QA Scout v{SCOUT_VERSION}" in output
    assert "parallel site execution is not implemented" in output
    assert "v1.0" not in output


def test_generated_client_artifacts_use_current_factory_version():
    state = QAFactoryState(project_id="claim-truth", mode="scaffold", raw_input="test")
    readme = PlaywrightGeneratorAgent._readme(state)
    summary = ReportBuilder().build_summary(state)
    assert f"Generated by AI QA Factory v{APP_VERSION}." in readme
    assert f"# AI QA Factory v{APP_VERSION} — Summary" in summary
    assert "v5.0.8 Model Routing Profiles" not in readme
    assert "v5.0.8 Model Routing Profiles" not in summary
