"""Phase 5N — Accessibility smoke runner.

Default mode: generates Playwright + axe-core TypeScript skeleton spec (no network calls).
Approved execution mode: same skeleton plus notes on how to execute (requires dual approval).

Safety invariants always enforced:
- No active network scan
- No exploit attempts
- No auth bypass
- No destructive actions
- human_review_required=True
- approved_for_delivery=False until human review
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from core.schemas.accessibility import (
    ACCESSIBILITY_CHECKS,
    WCAG_LEVELS,
    AccessibilityReport,
    AccessibilityViolation,
)

_SPEC_TEMPLATE = """\
// AUTO-GENERATED by AI QA Factory — Phase 5N Accessibility Smoke
// Target:     {target_url}
// WCAG Level: {wcag_level}
// Status:     planning_only — human review required before executing
//
// Prerequisites:
//   npm install @axe-core/playwright
//   npx playwright install chromium
//
// Run with:
//   npx playwright test {spec_filename} --grep @accessibility

import {{ test, expect }} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

const TARGET_URL = '{target_url}';

test.describe('Accessibility Smoke — WCAG {wcag_level} @accessibility', () => {{
{test_blocks}
  test('full page axe scan @accessibility @smoke', async ({{ page }}) => {{
    await page.goto(TARGET_URL);
    const results = await new AxeBuilder({{ page }})
      .withTags(['{wcag_tag}'])
      .analyze();
    // Review violations before treating as a hard failure
    // expect(results.violations).toHaveLength(0);
    console.log(`Violations found: ${{results.violations.length}}`);
    results.violations.forEach(v => {{
      console.log(`[${{v.impact}}] ${{v.id}} — ${{v.description}}`);
    }});
  }});
}});
"""

_CHECK_TEST = """\
  test('{check_name} @accessibility', async ({{ page }}) => {{
    await page.goto(TARGET_URL);
    const results = await new AxeBuilder({{ page }})
      .withRules(['{check_name}'])
      .analyze();
    expect(results.violations).toHaveLength(0);
  }});
"""

_WCAG_TAG_MAP = {"A": "wcag2a", "AA": "wcag2aa", "AAA": "wcag2aaa"}


class AccessibilityRunner:
    """Generates accessibility smoke plans and Playwright skeletons."""

    def __init__(
        self,
        project_id: str,
        target_url: str,
        outputs_root: str = "outputs",
        wcag_level: str = "AA",
    ) -> None:
        self.project_id = project_id
        self.target_url = target_url
        self.outputs_root = Path(outputs_root)
        self.wcag_level = wcag_level if wcag_level in WCAG_LEVELS else "AA"
        self._out_dir = self.outputs_root / project_id / "29_accessibility"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_plan(self, write_files: bool = True) -> AccessibilityReport:
        """Generate Playwright skeleton spec + planning report. No network calls."""
        spec_filename = "accessibility_smoke.generated.spec.ts"
        report = AccessibilityReport(
            project_id=self.project_id,
            generated_at=datetime.now(timezone.utc).isoformat(),
            target_url=self.target_url,
            wcag_level=self.wcag_level,
            checks_planned=list(ACCESSIBILITY_CHECKS),
            status="planning_only",
            notes=[
                "Skeleton spec generated — no execution performed.",
                f"Checks planned: {len(ACCESSIBILITY_CHECKS)} rules (WCAG {self.wcag_level}).",
                "Requires human review and explicit approval before execution.",
                "Run with: npx playwright test --grep @accessibility",
            ],
        )
        spec_content = self._generate_spec(spec_filename)
        if write_files:
            self._out_dir.mkdir(parents=True, exist_ok=True)
            spec_path = self._out_dir / spec_filename
            spec_path.write_text(spec_content, encoding="utf-8")
            report.generated_test_file = str(spec_path)
            (self._out_dir / "accessibility_report.json").write_text(
                json.dumps(report.to_dict(), indent=2, default=str), encoding="utf-8"
            )
            (self._out_dir / "accessibility_summary.md").write_text(
                self._generate_summary(report), encoding="utf-8"
            )
            (self._out_dir / "accessibility_violations.csv").write_text(
                self._generate_violations_csv([]), encoding="utf-8"
            )
        return report

    def execute(
        self,
        approve_public_readonly: bool = False,
        approve_browser_execution: bool = False,
        write_files: bool = True,
    ) -> AccessibilityReport:
        """Approved execution path — requires both approval flags.

        Generates the execution-ready skeleton and annotates the report with
        exact run commands. Actual browser automation runs via:
          npx playwright test <spec_file> --grep @accessibility
        """
        if not approve_public_readonly:
            raise ValueError(
                "Accessibility execution requires --approve-public-readonly-execution."
            )
        if not approve_browser_execution:
            raise ValueError(
                "Accessibility execution requires --approve-browser-execution."
            )
        report = self.generate_plan(write_files=write_files)
        spec_filename = "accessibility_smoke.generated.spec.ts"
        report.notes.append("Execution approved. Spec is ready to run.")
        report.notes.append(
            f"Run: npx playwright test {spec_filename} --grep @accessibility"
        )
        report.notes.append(
            "Findings will populate accessibility_violations.csv after execution."
        )
        return report

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _generate_spec(self, spec_filename: str) -> str:
        wcag_tag = _WCAG_TAG_MAP.get(self.wcag_level, "wcag2aa")
        test_blocks = "".join(
            _CHECK_TEST.format(check_name=c) for c in ACCESSIBILITY_CHECKS
        )
        return _SPEC_TEMPLATE.format(
            target_url=self.target_url,
            wcag_level=self.wcag_level,
            wcag_tag=wcag_tag,
            spec_filename=spec_filename,
            test_blocks=test_blocks,
        )

    def _generate_summary(self, report: AccessibilityReport) -> str:
        lines = [
            f"# Accessibility Smoke Summary — {report.project_id}",
            "",
            f"**Status:** {report.status}",
            f"**Target:** {report.target_url}",
            f"**WCAG Level:** {report.wcag_level}",
            f"**Generated:** {report.generated_at}",
            "",
            "## Planned Checks",
            "",
        ]
        for check in report.checks_planned:
            lines.append(f"- {check}")
        lines += [
            "",
            "## Notes",
            "",
        ]
        for note in report.notes:
            lines.append(f"- {note}")
        lines += [
            "",
            "> **DRAFT** — Generated checks only; execution requires approval.",
            "> Human review required before client delivery.",
        ]
        return "\n".join(lines) + "\n"

    @staticmethod
    def _generate_violations_csv(violations: list[AccessibilityViolation]) -> str:
        header = "rule_id,impact,description,element,url,wcag_criteria\n"
        rows = [
            ",".join([
                v.rule_id,
                v.impact,
                f'"{v.description}"',
                v.element,
                v.url,
                ";".join(v.wcag_criteria),
            ])
            for v in violations
        ]
        return header + "\n".join(rows)
