"""Phase 5M — API Test Generator.

Generates Playwright API test skeleton files from an APIContractReport.
Output files are planning artifacts — not auto-executable without human review.

Safety rules:
- Only safe_readonly endpoints get smoke test stubs by default
- requires_approval endpoints listed as commented-out stubs (skipped)
- blocked_by_default endpoints are excluded entirely
- No real API calls are made during generation
- executable_without_approval=False hardcoded in GeneratedTestsReport
"""
from __future__ import annotations

from pathlib import Path
from typing import List

from core.schemas.api_contract import (
    APIContractReport,
    GeneratedTestFile,
    GeneratedTestsReport,
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_TS_HEADER = """\
/// <reference types="node" />
import {{ test, expect }} from '@playwright/test';

// AUTO-GENERATED by AI QA Factory — Phase 5M API Test Generator
// Source contract: {source}
// Generated: planning artifact only — review before execution
// executable_without_approval=False — do not run without human review

const BASE_URL = process.env.API_BASE_URL || '{base_url}';
"""

_SMOKE_TEST_STUB = """\
  test('{method} {path} — returns non-5xx status', async ({{ request }}) => {{
    const res = await request.{method_lower}(`${{BASE_URL}}{path}`);
    expect(res.status()).toBeLessThan(500);
  }});
"""

_SCHEMA_TEST_STUB = """\
  test('{method} {path} — response is JSON', async ({{ request }}) => {{
    const res = await request.{method_lower}(`${{BASE_URL}}{path}`);
    if (res.status() < 400) {{
      const body = await res.json().catch(() => null);
      // TODO: assert body shape matches contract schema
      expect(body).not.toBeNull();
    }}
  }});
"""

_SKIPPED_STUB = """\
  // SKIPPED — requires_approval: {method} {path}
  // Uncomment and review before running:
  // test('{method} {path}', async ({{ request }}) => {{ ... }});
"""


def _ts_identifier(path: str, method: str) -> str:
    """Convert a path+method into a valid TS identifier fragment."""
    clean = path.replace("/", "_").replace("{", "").replace("}", "").strip("_")
    return f"{method.upper()}_{clean}"


# ---------------------------------------------------------------------------
# Generators
# ---------------------------------------------------------------------------

def _generate_smoke_spec(report: APIContractReport) -> str:
    """Generate Playwright API smoke test stubs for safe_readonly endpoints."""
    safe = [e for e in report.endpoints if e.safety_classification == "safe_readonly"]
    approval = [e for e in report.endpoints if e.safety_classification == "requires_approval"]

    header = _TS_HEADER.format(
        source=report.source_file or report.source_format,
        base_url=report.base_url or "http://localhost:3000",
    )
    lines = [header, "test.describe('API smoke — safe read-only endpoints', () => {"]

    for ep in safe:
        lines.append(_SMOKE_TEST_STUB.format(
            method=ep.method,
            method_lower=ep.method.lower(),
            path=ep.path,
        ))

    if approval:
        lines.append("\n  // --- Endpoints requiring approval (skipped) ---")
        for ep in approval[:10]:  # cap to avoid huge files
            lines.append(_SKIPPED_STUB.format(method=ep.method, path=ep.path))

    lines.append("});\n")
    return "\n".join(lines)


def _generate_schema_spec(report: APIContractReport) -> str:
    """Generate Playwright API schema validation test stubs."""
    safe = [e for e in report.endpoints if e.safety_classification == "safe_readonly"]

    header = _TS_HEADER.format(
        source=report.source_file or report.source_format,
        base_url=report.base_url or "http://localhost:3000",
    )
    lines = [header, "test.describe('API schema — response shape validation', () => {"]

    for ep in safe:
        lines.append(_SCHEMA_TEST_STUB.format(
            method=ep.method,
            method_lower=ep.method.lower(),
            path=ep.path,
        ))

    lines.append("});\n")
    return "\n".join(lines)


def _generate_negative_candidates(report: APIContractReport) -> str:
    """Generate a Markdown list of negative test candidates."""
    safe = [e for e in report.endpoints if e.safety_classification == "safe_readonly"]
    approval = [e for e in report.endpoints if e.safety_classification == "requires_approval"]
    blocked = [e for e in report.endpoints if e.safety_classification == "blocked_by_default"]

    lines = [
        "# API Negative Test Candidates",
        "",
        f"Source: `{report.source_file}`  ",
        f"Spec: {report.spec_title} {report.spec_version}",
        "",
        "## Safe read-only endpoints — negative cases",
        "",
        "These endpoints may be tested with invalid parameters, missing auth, or bad input:",
        "",
    ]
    for ep in safe:
        lines.append(f"- `{ep.method} {ep.path}` — try: missing required params, invalid param types, wrong auth")

    lines += [
        "",
        "## Endpoints requiring approval — plan only",
        "",
        "> These require human approval before negative testing.",
        "",
    ]
    for ep in approval:
        lines.append(f"- `{ep.method} {ep.path}` — {ep.safety_reason}")

    lines += [
        "",
        "## Blocked endpoints — do not test",
        "",
        "> These are blocked by default and must not be auto-executed.",
        "",
    ]
    for ep in blocked:
        lines.append(f"- `{ep.method} {ep.path}` — {ep.safety_reason}")

    lines += [
        "",
        "---",
        "_Generated by AI QA Factory Phase 5M — human review required before execution._",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

class APITestGenerator:
    """Generate Playwright API test skeletons from an APIContractReport."""

    def generate(
        self,
        report: APIContractReport,
        output_dir: str = "",
        write: bool = False,
    ) -> GeneratedTestsReport:
        """Generate all test artifact content and optionally write to disk."""
        safe_count = report.safe_readonly_count
        blocked_count = report.blocked_count

        smoke_content = _generate_smoke_spec(report)
        schema_content = _generate_schema_spec(report)
        negative_content = _generate_negative_candidates(report)

        generated_files: List[GeneratedTestFile] = [
            GeneratedTestFile(
                filename="api_smoke.generated.spec.ts",
                artifact_dir=output_dir,
                test_type="smoke",
                endpoint_count=safe_count,
                notes="Safe read-only endpoints only",
            ),
            GeneratedTestFile(
                filename="api_schema.generated.spec.ts",
                artifact_dir=output_dir,
                test_type="schema",
                endpoint_count=safe_count,
                notes="Schema validation stubs for safe endpoints",
            ),
            GeneratedTestFile(
                filename="api_negative_candidates.md",
                artifact_dir=output_dir,
                test_type="negative",
                endpoint_count=report.total_endpoints,
                notes="Negative test planning — not auto-executable",
            ),
        ]

        if write and output_dir:
            out = Path(output_dir)
            out.mkdir(parents=True, exist_ok=True)
            (out / "api_smoke.generated.spec.ts").write_text(smoke_content, encoding="utf-8")
            (out / "api_schema.generated.spec.ts").write_text(schema_content, encoding="utf-8")
            (out / "api_negative_candidates.md").write_text(negative_content, encoding="utf-8")

        return GeneratedTestsReport(
            project_id=report.project_id,
            source_contract_file=report.source_file,
            generated_files=generated_files,
            total_test_stubs=safe_count * 2,  # smoke + schema per safe endpoint
            safe_endpoints_covered=safe_count,
            skipped_blocked_endpoints=blocked_count,
            notes=[
                f"Generated smoke + schema stubs for {safe_count} safe endpoints",
                f"Skipped {blocked_count} blocked endpoints",
                "All stubs are planning artifacts — executable_without_approval=False",
            ],
        )

    def get_smoke_content(self, report: APIContractReport) -> str:
        return _generate_smoke_spec(report)

    def get_schema_content(self, report: APIContractReport) -> str:
        return _generate_schema_spec(report)

    def get_negative_content(self, report: APIContractReport) -> str:
        return _generate_negative_candidates(report)
