"""Phase 5M — CI/CD Builder.

Generates CI/CD pipeline configuration files (GitHub Actions, GitLab CI) for
running Playwright smoke tests in a CI environment.

Safety rules:
- auto_pr_creation_allowed=False hardcoded in CICDConfig
- client_repo_writeback_allowed=False hardcoded
- production_deploy_allowed=False hardcoded
- Generated configs are planning artifacts — must be reviewed before use
- No credentials, secrets, or tokens embedded in generated configs
"""
from __future__ import annotations

import json
from pathlib import Path

from core.schemas.api_contract import CICDConfig, CICDManifest

# ---------------------------------------------------------------------------
# GitHub Actions template
# ---------------------------------------------------------------------------

_GITHUB_ACTIONS_TEMPLATE = """\
# AUTO-GENERATED by AI QA Factory — Phase 5M CI/CD Builder
# Project: {project_id}
# Review before committing to your repository.
# Do NOT embed secrets or credentials in this file — use GitHub Secrets instead.

name: QA Smoke Tests

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  qa-smoke:
    name: Playwright API + Browser Smoke
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: {scaffold_root}/package.json

      - name: Install Playwright dependencies
        working-directory: {scaffold_root}
        run: npm ci

      - name: Install Playwright browsers
        working-directory: {scaffold_root}
        run: npx playwright install --with-deps chromium

      - name: Run smoke tests
        working-directory: {scaffold_root}
        run: npx playwright test tests/smoke --config playwright.config.cjs --reporter=list
        env:
          CI: true
          # API_BASE_URL: ${{{{ secrets.API_BASE_URL }}}}  # Uncomment if needed

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: {scaffold_root}/playwright-report/
          retention-days: 7

      - name: Upload test results (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: {scaffold_root}/test-results/
          retention-days: 3
"""

# ---------------------------------------------------------------------------
# GitLab CI template
# ---------------------------------------------------------------------------

_GITLAB_CI_TEMPLATE = """\
# AUTO-GENERATED by AI QA Factory — Phase 5M CI/CD Builder
# Project: {project_id}
# Review before committing to your repository.
# Do NOT embed secrets or credentials in this file — use GitLab CI Variables instead.

image: mcr.microsoft.com/playwright:v1.40.0-jammy

stages:
  - smoke

variables:
  CI: "true"

qa-smoke:
  stage: smoke
  before_script:
    - cd {scaffold_root}
    - npm ci
  script:
    - npx playwright test tests/smoke --config playwright.config.cjs --reporter=list
  artifacts:
    when: always
    paths:
      - {scaffold_root}/playwright-report/
      - {scaffold_root}/test-results/
    expire_in: 7 days
  only:
    - main
    - master
    - merge_requests
"""

# ---------------------------------------------------------------------------
# CI/CD summary template
# ---------------------------------------------------------------------------

_SUMMARY_TEMPLATE = """\
# CI/CD Configuration Summary

**Project:** {project_id}
**Platform:** {platform}
**Generated:** AI QA Factory Phase 5M

## Generated Files

{file_list}

## Steps Included

{steps}

## How to Use

1. Review the generated workflow file carefully.
2. Copy it to your repository at the path shown above.
3. Configure any required secrets in your CI/CD platform settings.
4. Do NOT embed real credentials or API keys in the config file.
5. Run a test build manually before enabling automatic triggers.

## Safety Notes

- `auto_pr_creation_allowed=False` — this tool does not create PRs or push to your repo
- `client_repo_writeback_allowed=False` — generated files must be manually copied
- `production_deploy_allowed=False` — no deployment steps are included
- `human_review_required=True` — always review before committing to CI

---
_Generated by AI QA Factory — human review required before use._
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

class CICDBuilder:
    """Generate CI/CD pipeline configuration files."""

    def build(
        self,
        project_id: str,
        platform: str = "github_actions",
        scaffold_root: str = "03_framework/playwright",
        output_dir: str = "",
        write: bool = False,
    ) -> CICDConfig:
        """Generate a CI/CD config for the given platform."""
        platform = platform.lower()

        if platform == "github_actions":
            workflow_filename = ".github/workflows/qa-smoke.yml"
            workflow_content = _GITHUB_ACTIONS_TEMPLATE.format(
                project_id=project_id,
                scaffold_root=scaffold_root,
            )
            steps = [
                "checkout", "setup-node", "npm-ci",
                "playwright-install", "smoke-tests",
                "upload-playwright-report", "upload-test-results",
            ]
        elif platform == "gitlab_ci":
            workflow_filename = ".gitlab-ci.yml"
            workflow_content = _GITLAB_CI_TEMPLATE.format(
                project_id=project_id,
                scaffold_root=scaffold_root,
            )
            steps = ["npm-ci", "playwright-smoke", "artifacts-upload"]
        else:
            workflow_filename = f"cicd-{platform}.yml"
            workflow_content = f"# Platform '{platform}' — planning only\n# Implement manually.\n"
            steps = []

        config = CICDConfig(
            project_id=project_id,
            platform=platform,
            workflow_filename=workflow_filename,
            workflow_content=workflow_content,
            scaffold_root=scaffold_root,
            steps_included=steps,
            notes=[
                f"Generated {platform} workflow for project {project_id}",
                "Review before committing — do not embed secrets",
            ],
        )

        if write and output_dir:
            self._write_artifacts(config, output_dir)

        return config

    def build_manifest(
        self,
        config: CICDConfig,
        output_dir: str = "",
        write: bool = False,
    ) -> CICDManifest:
        """Build a CICDManifest summarising the generated artifacts."""
        artifacts = [config.workflow_filename, "cicd_summary.md", "cicd_manifest.json"]

        manifest = CICDManifest(
            project_id=config.project_id,
            platform=config.platform,
            artifacts=artifacts,
            scaffold_root=config.scaffold_root,
            notes=config.notes[:],
        )

        if write and output_dir:
            summary = _SUMMARY_TEMPLATE.format(
                project_id=config.project_id,
                platform=config.platform,
                file_list="\n".join(f"- `{a}`" for a in artifacts),
                steps="\n".join(f"- {s}" for s in config.steps_included),
            )
            out = Path(output_dir)
            out.mkdir(parents=True, exist_ok=True)
            (out / "cicd_summary.md").write_text(summary, encoding="utf-8")
            manifest_dict = {
                "project_id": manifest.project_id,
                "platform": manifest.platform,
                "artifacts": manifest.artifacts,
                "scaffold_root": manifest.scaffold_root,
                "notes": manifest.notes,
                "auto_pr_creation_allowed": False,
                "client_repo_writeback_allowed": False,
                "human_review_required": True,
            }
            (out / "cicd_manifest.json").write_text(
                json.dumps(manifest_dict, indent=2), encoding="utf-8"
            )

        return manifest

    def _write_artifacts(self, config: CICDConfig, output_dir: str) -> None:
        """Write workflow file and summary to output_dir."""
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        # Write workflow YAML
        workflow_path = out / Path(config.workflow_filename).name
        workflow_path.write_text(config.workflow_content, encoding="utf-8")

        # Write summary
        summary = _SUMMARY_TEMPLATE.format(
            project_id=config.project_id,
            platform=config.platform,
            file_list=f"- `{config.workflow_filename}`\n- `cicd_summary.md`\n- `cicd_manifest.json`",
            steps="\n".join(f"- {s}" for s in config.steps_included),
        )
        (out / "cicd_summary.md").write_text(summary, encoding="utf-8")
