"""FrameworkScaffoldGenerator — builds a local Playwright TypeScript scaffold.

Phase 3A — scaffold generation only:
- No URL fetching.
- No browser execution.
- No Playwright execution.
- No npm/npx execution.
- No TypeScript compilation.
- No credential use.
- No external calls.
- No test execution.
- Generated scaffold requires human review before any local validation.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import List, Optional

from core.schemas.framework_scaffold import FrameworkFile, FrameworkScaffold, FrameworkScaffoldPlan
from core.schemas.project_blueprint import ProjectBlueprint
from core.schemas.qa_strategy import QAStrategy


# ---------------------------------------------------------------------------
# FrameworkScaffoldGenerator
# ---------------------------------------------------------------------------

class FrameworkScaffoldGenerator:
    """Generates a local Playwright TypeScript scaffold from blueprint + strategy."""

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def build_scaffold_plan(
        self,
        blueprint: ProjectBlueprint,
        strategy: Optional[QAStrategy] = None,
    ) -> FrameworkScaffoldPlan:
        fw_type = self._decide_framework_type(blueprint, strategy)
        included, deferred, blocked = self._categorise_layers(blueprint, strategy)
        structure = self._recommended_structure(blueprint, strategy)
        approvals = list(blueprint.required_approvals) if blueprint.required_approvals else [
            "Target URL approval required before any test execution.",
            "Test credential approval required before auth testing.",
        ]
        return FrameworkScaffoldPlan(
            project_id=blueprint.project_id,
            target_framework=fw_type,
            recommended_structure=structure,
            included_layers=included,
            deferred_layers=deferred,
            blocked_layers=blocked,
            required_approvals=approvals,
            notes=[
                "Scaffold generation is local file generation only.",
                "No tests are executed in Phase 3A.",
                "Run docs/SCAFFOLD_REVIEW_CHECKLIST.md before any local validation.",
            ],
        )

    def generate_scaffold(
        self,
        blueprint: ProjectBlueprint,
        strategy: Optional[QAStrategy] = None,
        out_dir: Optional[Path] = None,
    ) -> FrameworkScaffold:
        if out_dir is None:
            out_dir = Path("outputs") / blueprint.project_id / "03_framework" / "playwright"
        out_dir = Path(out_dir)

        fw_type = self._decide_framework_type(blueprint, strategy)
        proj_name = self._sanitize_project_name(
            blueprint.project_name or blueprint.project_id
        )
        files: List[FrameworkFile] = []

        manifest = self._get_file_manifest(blueprint, strategy)
        for entry in manifest:
            rel_path = entry["path"]
            ftype = entry["file_type"]
            purpose = entry["purpose"]
            content = self._generate_file_content(rel_path, blueprint, strategy, proj_name)
            dest = out_dir / rel_path
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content, encoding="utf-8")
            files.append(FrameworkFile(
                id=f"ff-{len(files)+1:03d}",
                path="03_framework/playwright/" + rel_path.replace("\\", "/"),
                purpose=purpose,
                file_type=ftype,
                client_visible=False,
                generated=True,
                requires_review=True,
            ))

        generated_from = ["ProjectBlueprint"]
        if strategy is not None:
            generated_from.append("QAStrategy")

        scaffold = FrameworkScaffold(
            project_id=blueprint.project_id,
            framework_type=fw_type,
            language="typescript",
            test_runner="playwright",
            root_path=str(out_dir),
            files=files,
            generated_from=generated_from,
            scaffold_status="generated",
            client_visible=False,
            requires_review=True,
            execution_allowed=False,
            notes=[
                "Scaffold generated by FrameworkScaffoldGenerator (Phase 3A).",
                "No tests have been executed.",
                "No URLs have been fetched.",
                "No credentials have been used.",
                "Review SCAFFOLD_REVIEW_CHECKLIST.md before any local validation.",
                "execution_allowed=False — explicit approval required before running.",
            ],
        )

        # Write FRAMEWORK_SCAFFOLD.json + .md into the root
        self._write_scaffold_metadata(scaffold, out_dir)
        return scaffold

    def render_scaffold_artifacts(
        self,
        scaffold: FrameworkScaffold,
        out_dir: Path,
    ) -> dict:
        """Write FRAMEWORK_SCAFFOLD.json and .md; return {name: path} dict."""
        out_dir = Path(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        self._write_scaffold_metadata(scaffold, out_dir)
        json_path = out_dir / "FRAMEWORK_SCAFFOLD.json"
        md_path = out_dir / "FRAMEWORK_SCAFFOLD.md"
        return {
            "framework_scaffold_json": str(json_path),
            "framework_scaffold_md": str(md_path),
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _sanitize_project_name(self, name: str) -> str:
        name = re.sub(r"[^\w\s-]", "", name.lower())
        name = re.sub(r"[\s_]+", "-", name.strip())
        name = re.sub(r"-+", "-", name)
        return name[:50] or "qa-project"

    def _decide_framework_type(
        self, blueprint: ProjectBlueprint, strategy: Optional[QAStrategy]
    ) -> str:
        pt = blueprint.project_type
        if pt == "api_backend":
            return "api_only"
        if pt == "mixed_ui_api":
            return "mixed_ui_api"
        return "playwright_ts"

    def _has_layer(self, strategy: Optional[QAStrategy], layer_name: str) -> bool:
        if strategy is None:
            return False
        for tl in strategy.test_layers:
            if tl.layer.lower() == layer_name.lower() and tl.recommended and not tl.blocked:
                return True
        return False

    def _has_any_signal(self, blueprint: ProjectBlueprint, *signals: str) -> bool:
        text = " ".join([
            blueprint.project_type or "",
            blueprint.client_goal or "",
            blueprint.scope_notes or "",
            " ".join(blueprint.risk_areas),
            " ".join(blueprint.application_surfaces),
        ]).lower()
        return any(s.lower() in text for s in signals)

    def _categorise_layers(self, blueprint, strategy):
        included, deferred, blocked = [], [], []
        if strategy is None:
            return ["smoke", "ui", "manual_exploratory"], ["api", "visual", "performance"], ["mobile_native"]
        for tl in strategy.test_layers:
            if tl.blocked:
                blocked.append(tl.layer)
            elif tl.recommended:
                included.append(tl.layer)
            else:
                deferred.append(tl.layer)
        return included, deferred, blocked

    def _recommended_structure(self, blueprint, strategy) -> list:
        lines = [
            "03_framework/playwright/",
            "  package.json",
            "  tsconfig.json",
            "  playwright.config.ts",
            "  .gitignore",
            "  .env.example",
            "  README.md",
            "  tests/smoke/smoke.spec.ts",
            "  tests/regression/regression-placeholder.spec.ts",
            "  pages/BasePage.ts",
            "  fixtures/test-fixtures.ts",
            "  utils/env.ts",
            "  utils/test-data.ts",
            "  test-data/README.md",
            "  test-data/sample-users.example.json",
            "  docs/TEST_STRATEGY.md",
            "  docs/HOW_TO_RUN.md",
            "  docs/SCAFFOLD_REVIEW_CHECKLIST.md",
        ]
        pt = blueprint.project_type
        has_auth = self._has_layer(strategy, "auth") or pt in ("auth_heavy", "web_saas")
        has_api = self._has_layer(strategy, "api") or pt == "api_backend"
        if has_auth:
            lines.append("  tests/auth/auth-placeholder.spec.ts")
            lines.append("  pages/LoginPage.ts")
        if has_api:
            lines.append("  tests/api/api-placeholder.spec.ts")
            lines.append("  utils/api-client.ts")
        if pt in ("web_saas", "admin_panel", "ecommerce"):
            lines.append("  pages/DashboardPage.ts")
        if pt == "ecommerce":
            lines.append("  tests/ecommerce/checkout-placeholder.spec.ts")
        if pt == "admin_panel":
            lines.append("  tests/admin/admin-placeholder.spec.ts")
        return lines

    def _get_file_manifest(self, blueprint, strategy) -> list:
        pt = blueprint.project_type
        has_auth = self._has_layer(strategy, "auth") or pt in ("auth_heavy", "web_saas")
        has_api = self._has_layer(strategy, "api") or pt in ("api_backend", "mixed_ui_api")
        has_dashboard = pt in ("web_saas", "admin_panel", "ecommerce")

        manifest = [
            {"path": "package.json",           "file_type": "package_json",      "purpose": "Node.js project definition with Playwright scripts"},
            {"path": "tsconfig.json",           "file_type": "tsconfig",          "purpose": "TypeScript compiler configuration"},
            {"path": "playwright.config.ts",    "file_type": "playwright_config", "purpose": "Playwright test runner configuration — reads BASE_URL from env"},
            {"path": ".gitignore",              "file_type": "gitignore",         "purpose": "Ignore node_modules, test-results, .env"},
            {"path": ".env.example",            "file_type": "example_env",       "purpose": "Placeholder env vars — copy to .env, never commit .env"},
            {"path": "README.md",               "file_type": "documentation",     "purpose": "Scaffold overview, setup, approval requirements"},
            {"path": "tests/smoke/smoke.spec.ts",              "file_type": "test_spec",    "purpose": "Smoke test — homepage/app availability placeholder"},
            {"path": "tests/regression/regression-placeholder.spec.ts", "file_type": "test_spec", "purpose": "Regression suite placeholder"},
            {"path": "pages/BasePage.ts",       "file_type": "page_object",       "purpose": "Base page object with shared helpers"},
            {"path": "fixtures/test-fixtures.ts", "file_type": "fixture",         "purpose": "Playwright test fixtures"},
            {"path": "utils/env.ts",            "file_type": "utility",           "purpose": "Safe env var reader with validation"},
            {"path": "utils/test-data.ts",      "file_type": "utility",           "purpose": "Test data factory — no real credentials"},
            {"path": "test-data/README.md",     "file_type": "documentation",     "purpose": "Test data governance — no real secrets"},
            {"path": "test-data/sample-users.example.json", "file_type": "test_data", "purpose": "Sample user structure — placeholders only"},
            {"path": "docs/TEST_STRATEGY.md",   "file_type": "documentation",     "purpose": "Strategy summary from QAStrategy"},
            {"path": "docs/HOW_TO_RUN.md",      "file_type": "documentation",     "purpose": "Setup and run guide with approval checklist"},
            {"path": "docs/SCAFFOLD_REVIEW_CHECKLIST.md", "file_type": "documentation", "purpose": "Pre-execution safety checklist"},
        ]
        if has_auth:
            manifest += [
                {"path": "tests/auth/auth-placeholder.spec.ts", "file_type": "test_spec", "purpose": "Auth flow placeholder — requires test account approval"},
                {"path": "pages/LoginPage.ts",   "file_type": "page_object",       "purpose": "Login page object template"},
            ]
        if has_api:
            manifest += [
                {"path": "tests/api/api-placeholder.spec.ts", "file_type": "test_spec", "purpose": "API test placeholder — requires API_BASE_URL approval"},
                {"path": "utils/api-client.ts",  "file_type": "utility",           "purpose": "Playwright request-context API client wrapper"},
            ]
        if has_dashboard:
            manifest.append({"path": "pages/DashboardPage.ts", "file_type": "page_object", "purpose": "Dashboard page object template"})
        if pt == "ecommerce":
            manifest.append({"path": "tests/ecommerce/checkout-placeholder.spec.ts", "file_type": "test_spec", "purpose": "Checkout flow placeholder — requires sandbox approval"})
        if pt == "admin_panel":
            manifest.append({"path": "tests/admin/admin-placeholder.spec.ts", "file_type": "test_spec", "purpose": "Admin panel placeholder — requires admin account approval"})
        return manifest

    def _generate_file_content(
        self,
        rel_path: str,
        blueprint: ProjectBlueprint,
        strategy: Optional[QAStrategy],
        proj_name: str,
    ) -> str:
        dispatch = {
            "package.json":           lambda: self._gen_package_json(proj_name),
            "tsconfig.json":          lambda: self._gen_tsconfig(),
            "playwright.config.ts":   lambda: self._gen_playwright_config(blueprint, strategy),
            ".gitignore":             lambda: self._gen_gitignore(),
            ".env.example":           lambda: self._gen_env_example(blueprint),
            "README.md":              lambda: self._gen_readme(blueprint, strategy, proj_name),
            "tests/smoke/smoke.spec.ts":           lambda: self._gen_smoke_spec(blueprint),
            "tests/regression/regression-placeholder.spec.ts": lambda: self._gen_regression_spec(blueprint, strategy),
            "tests/auth/auth-placeholder.spec.ts": lambda: self._gen_auth_spec(blueprint),
            "tests/api/api-placeholder.spec.ts":   lambda: self._gen_api_spec(blueprint),
            "tests/ecommerce/checkout-placeholder.spec.ts": lambda: self._gen_checkout_spec(),
            "tests/admin/admin-placeholder.spec.ts": lambda: self._gen_admin_spec(),
            "pages/BasePage.ts":       lambda: self._gen_base_page(),
            "pages/LoginPage.ts":      lambda: self._gen_login_page(),
            "pages/DashboardPage.ts":  lambda: self._gen_dashboard_page(),
            "fixtures/test-fixtures.ts": lambda: self._gen_fixtures(blueprint),
            "utils/env.ts":            lambda: self._gen_env_util(),
            "utils/test-data.ts":      lambda: self._gen_test_data_util(blueprint),
            "utils/api-client.ts":     lambda: self._gen_api_client(),
            "test-data/README.md":     lambda: self._gen_test_data_readme(),
            "test-data/sample-users.example.json": lambda: self._gen_sample_users(),
            "docs/TEST_STRATEGY.md":   lambda: self._gen_test_strategy_doc(blueprint, strategy),
            "docs/HOW_TO_RUN.md":      lambda: self._gen_how_to_run(blueprint),
            "docs/SCAFFOLD_REVIEW_CHECKLIST.md": lambda: self._gen_review_checklist(blueprint, strategy),
        }
        fn = dispatch.get(rel_path)
        if fn:
            return fn()
        return f"// Generated placeholder for {rel_path}\n// Review before use.\n"

    # ------------------------------------------------------------------
    # File content generators
    # ------------------------------------------------------------------

    def _gen_package_json(self, proj_name: str) -> str:
        data = {
            "name": f"qa-automation-{proj_name}",
            "version": "1.0.0",
            "description": "QA automation scaffold — review before running. Generated by QA Workbench Phase 3A.",
            "private": True,
            "scripts": {
                "test":         "playwright test",
                "test:smoke":   "playwright test tests/smoke",
                "test:api":     "playwright test tests/api",
                "test:headed":  "playwright test --headed",
                "test:ui":      "playwright test --ui",
                "report":       "playwright show-report",
                "typecheck":    "tsc --noEmit",
            },
            "devDependencies": {
                "@playwright/test": "^1.48.0",
                "typescript":       "^5.3.0",
                "dotenv":           "^16.4.0",
            },
        }
        return json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    def _gen_tsconfig(self) -> str:
        data = {
            "compilerOptions": {
                "target":                          "ES2020",
                "module":                          "commonjs",
                "lib":                             ["ES2020"],
                "strict":                          True,
                "esModuleInterop":                 True,
                "skipLibCheck":                    True,
                "forceConsistentCasingInFileNames": True,
                "resolveJsonModule":               True,
                "outDir":                          "dist",
            },
            "include": ["**/*.ts"],
            "exclude": ["node_modules", "dist", "test-results"],
        }
        return json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    def _gen_playwright_config(
        self, blueprint: ProjectBlueprint, strategy: Optional[QAStrategy]
    ) -> str:
        has_mobile = self._has_layer(strategy, "mobile_web")
        mobile_comment = ""
        if has_mobile:
            mobile_comment = """
    // Mobile web emulation (optional — uncomment after approval):
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 13'] },
    // },"""

        return f"""import {{ defineConfig, devices }} from '@playwright/test';
import * as dotenv from 'dotenv';

dotenv.config();

/**
 * Playwright configuration — generated by QA Workbench Phase 3A.
 *
 * IMPORTANT: Do not run against external/staging/production URLs
 * without completing docs/SCAFFOLD_REVIEW_CHECKLIST.md.
 *
 * BASE_URL must be set in .env and approved as a test target.
 * Default 'http://localhost:3000' is a placeholder only.
 *
 * execution_allowed=False — requires explicit approval before running.
 */
export default defineConfig({{
  testDir: './tests',
  outputDir: './test-results',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [['html'], ['list']],

  use: {{
    // BASE_URL must be explicitly set and approved before running.
    // Do not hardcode target URLs here.
    baseURL: process.env.BASE_URL || 'http://localhost:3000',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  }},

  projects: [
    {{
      name: 'chromium',
      use: {{ ...devices['Desktop Chrome'] }},
    }},
    // Uncomment after smoke suite is stable:
    // {{
    //   name: 'firefox',
    //   use: {{ ...devices['Desktop Firefox'] }},
    // }},
    // {{
    //   name: 'webkit',
    //   use: {{ ...devices['Desktop Safari'] }},
    // }},{mobile_comment}
  ],
}});
"""

    def _gen_gitignore(self) -> str:
        return """# Dependencies
node_modules/

# Playwright outputs
test-results/
playwright-report/
dist/

# Environment — NEVER commit real .env files
.env
.env.local
.env.*.local

# OS
.DS_Store
Thumbs.db
"""

    def _gen_env_example(self, blueprint: ProjectBlueprint) -> str:
        pt = blueprint.project_type
        lines = [
            "# Environment variables — copy to .env, fill in AFTER target approval.",
            "# NEVER commit .env files with real values.",
            "# See docs/SCAFFOLD_REVIEW_CHECKLIST.md before setting any values.",
            "",
            "# Target application URL — set only after explicit approval.",
            "# Do not set to a real URL without completing the approval checklist.",
            "BASE_URL=http://localhost:3000",
            "",
        ]
        if pt in ("web_saas", "auth_heavy", "ecommerce", "admin_panel", "mixed_ui_api", "ai_generated_app"):
            lines += [
                "# Test credentials — synthetic test accounts ONLY. Never real user accounts.",
                "# Obtain approval before using any credentials.",
                "TEST_USERNAME=test-user@example.com",
                "TEST_PASSWORD=PLACEHOLDER_DO_NOT_USE",
                "",
            ]
        if pt in ("api_backend", "mixed_ui_api") or blueprint.project_type == "api_backend":
            lines += [
                "# API base URL — set only after explicit approval.",
                "API_BASE_URL=http://localhost:3001",
                "",
            ]
        if pt == "ecommerce":
            lines += [
                "# Payment sandbox — confirm sandbox mode in writing before ANY payment testing.",
                "PAYMENT_SANDBOX=true",
                "STRIPE_TEST_KEY=PLACEHOLDER_DO_NOT_USE",
                "",
            ]
        lines += [
            "# CI environment flag",
            "CI=false",
        ]
        return "\n".join(lines) + "\n"

    def _gen_readme(
        self, blueprint: ProjectBlueprint, strategy: Optional[QAStrategy], proj_name: str
    ) -> str:
        pt = blueprint.project_type
        env = blueprint.environment or "unknown"
        layers_str = ""
        if strategy:
            rec = [tl.layer for tl in strategy.test_layers if tl.recommended and not tl.blocked]
            layers_str = ", ".join(rec) if rec else "smoke, ui"
        else:
            layers_str = "smoke, ui"

        return f"""# QA Automation Scaffold — {proj_name}

> **Generated scaffold — not yet executed. Review required before running.**

---

## What this is

This is a Playwright TypeScript automation scaffold generated by the QA Workbench (Phase 3A).
It is a starting point for client QA automation work — not a completed, executed test suite.

| Field            | Value |
|---|---|
| Project ID       | `{blueprint.project_id}` |
| Project type     | `{pt}` |
| Environment      | `{env}` |
| Generated from   | QA Strategy (Phase 2C) + Project Blueprint (Phase 2B) |
| Execution status | **Not executed** |
| Approval status  | **Pending — see checklist** |

---

## Before running anything

**Complete `docs/SCAFFOLD_REVIEW_CHECKLIST.md` before running any command.**

You must confirm:
- [ ] Target URL is approved for testing
- [ ] Environment is confirmed (staging, not production)
- [ ] Credentials are synthetic test accounts, not real users
- [ ] No payment flows run without sandbox confirmation
- [ ] No admin/destructive actions without explicit scope approval

---

## Setup

```bash
# 1. Install dependencies (after review — Phase 3A only generates, does not install)
npm install

# 2. Install Playwright browsers (after install)
npx playwright install

# 3. Copy .env.example and set your approved values
cp .env.example .env
# Edit .env — set BASE_URL to your approved test target
```

---

## Environment variables

| Variable          | Purpose                              | Notes |
|---|---|---|
| `BASE_URL`        | Target application URL               | Must be approved before use |
| `TEST_USERNAME`   | Test account email                   | Synthetic account only |
| `TEST_PASSWORD`   | Test account password                | Synthetic account only |
| `API_BASE_URL`    | API base URL (if applicable)         | Must be approved before use |

---

## Running tests (after approval and setup)

```bash
# TypeScript check (safe — no execution against external URLs)
npm run typecheck

# Smoke tests (requires BASE_URL and approval)
npm run test:smoke

# All tests
npm run test

# Headed mode (useful for debugging)
npm run test:headed

# View report
npm run report
```

---

## Recommended test layers

{layers_str}

See `docs/TEST_STRATEGY.md` for full layer breakdown.

---

## What to customise

- Update selectors in `pages/` — no selectors can be guessed without inspecting the real application.
- Add real test data to `utils/test-data.ts` — never hardcode credentials.
- Expand smoke spec with actual page title / landmark after approval.
- Review auth spec if auth testing is in scope.
- Remove placeholder comments once flows are confirmed.

---

## What is intentionally placeholder

- `tests/smoke/smoke.spec.ts` — awaits real application URL and confirmed page title.
- `tests/auth/` — awaits approved test credentials and confirmed selectors.
- `tests/api/` — awaits approved API_BASE_URL and confirmed endpoints.
- `pages/*.ts` — skeleton structure; real selectors must be added after inspection.

---

_Generated by QA Workbench Phase 3A. No tests have been executed. No URLs have been fetched. No credentials have been used._
"""

    def _gen_smoke_spec(self, blueprint: ProjectBlueprint) -> str:
        return f"""import {{ test, expect }} from '@playwright/test';

/**
 * Smoke suite — {blueprint.project_id}
 *
 * IMPORTANT: Do not run against external/staging/production URLs
 * without completing docs/SCAFFOLD_REVIEW_CHECKLIST.md.
 *
 * BASE_URL must be set in .env and approved as a test target.
 * These tests are placeholders — customise before executing.
 */
test.describe('Smoke Suite', () => {{
  test('application is reachable and returns a page', async ({{ page }}) => {{
    // TODO: Confirm BASE_URL is set to approved test target before running.
    // TODO: Replace title matcher with the actual application title after inspection.
    await page.goto('/');
    await expect(page).toHaveTitle(/.+/);
  }});

  test('primary navigation renders without errors', async ({{ page }}) => {{
    // TODO: Replace with actual selector after inspecting the real application.
    await page.goto('/');
    await expect(page.locator('body')).toBeVisible();
    // TODO: Add specific navigation element check, e.g.:
    // await expect(page.locator('nav')).toBeVisible();
  }});
}});
"""

    def _gen_auth_spec(self, blueprint: ProjectBlueprint) -> str:
        return f"""import {{ test, expect }} from '@playwright/test';
import {{ getEnv }} from '../../utils/env';

/**
 * Auth flow placeholder — {blueprint.project_id}
 *
 * IMPORTANT: Credential use requires explicit approval.
 * TEST_USERNAME and TEST_PASSWORD must be synthetic test accounts — never real users.
 * Complete docs/SCAFFOLD_REVIEW_CHECKLIST.md before enabling this suite.
 *
 * Tests are skipped by default until approval is obtained.
 */

test.describe('Auth Suite', () => {{
  // Skip entire suite until credentials and target URL are approved.
  test.skip(
    !process.env.TEST_USERNAME || !process.env.TEST_PASSWORD,
    'Auth tests require TEST_USERNAME and TEST_PASSWORD — set after approval only.'
  );

  test('login with valid test credentials', async ({{ page }}) => {{
    // TODO: Replace selectors with actual application selectors after inspection.
    // Credential approval is required before running this test.
    const username = getEnv('TEST_USERNAME');
    const password = getEnv('TEST_PASSWORD');

    await page.goto('/login');
    // TODO: Replace with actual selector:
    await page.locator('[data-testid="email"]').fill(username);
    await page.locator('[data-testid="password"]').fill(password);
    await page.locator('[data-testid="submit"]').click();

    // TODO: Replace with actual post-login assertion:
    await expect(page).toHaveURL(/dashboard|home|app/);
  }});

  test('protected route redirects unauthenticated user', async ({{ page }}) => {{
    // TODO: Replace with actual protected route URL.
    await page.goto('/dashboard');
    // TODO: Replace with actual login redirect assertion:
    await expect(page).toHaveURL(/login|auth|signin/);
  }});

  test('logout clears session', async ({{ page }}) => {{
    // TODO: Implement logout flow after login flow is confirmed.
    test.skip(true, 'Implement after login flow is confirmed and approved.');
  }});
}});
"""

    def _gen_api_spec(self, blueprint: ProjectBlueprint) -> str:
        return f"""import {{ test, expect }} from '@playwright/test';

/**
 * API test placeholder — {blueprint.project_id}
 *
 * IMPORTANT: API_BASE_URL must be set and approved before running.
 * These tests use Playwright request context — no browser required.
 * Complete docs/SCAFFOLD_REVIEW_CHECKLIST.md before enabling this suite.
 *
 * Tests are skipped by default until API_BASE_URL is approved.
 */

test.describe('API Suite', () => {{
  test.skip(
    !process.env.API_BASE_URL,
    'API tests require API_BASE_URL to be set and approved.'
  );

  test('health endpoint returns 200', async ({{ request }}) => {{
    // TODO: Replace '/health' with the actual health check endpoint.
    // This is a placeholder — confirm endpoint path before running.
    const apiBase = process.env.API_BASE_URL || 'http://localhost:3001';
    const response = await request.get(`${{apiBase}}/health`);
    expect(response.status()).toBe(200);
  }});

  test('authenticated endpoint requires auth header', async ({{ request }}) => {{
    // TODO: Replace with actual protected endpoint.
    // Auth header validation placeholder.
    const apiBase = process.env.API_BASE_URL || 'http://localhost:3001';
    const response = await request.get(`${{apiBase}}/api/protected`);
    // Expect 401 without auth header:
    expect(response.status()).toBe(401);
  }});

  test('POST with valid body returns 201', async ({{ request }}) => {{
    // TODO: Replace with actual endpoint and request body after API docs review.
    test.skip(true, 'Implement after API contract is confirmed and approved.');
  }});
}});
"""

    def _gen_regression_spec(
        self, blueprint: ProjectBlueprint, strategy: Optional[QAStrategy]
    ) -> str:
        surfaces = blueprint.application_surfaces or ["dashboard", "forms", "navigation"]
        surface_todos = "\n".join(
            f"  // TODO: Add regression test for surface: {s}" for s in surfaces[:6]
        )
        return f"""import {{ test, expect }} from '@playwright/test';

/**
 * Regression suite placeholder — {blueprint.project_id}
 *
 * This file is a placeholder for regression tests.
 * Build regression suite after smoke suite is stable and approved.
 *
 * Identified surfaces to cover:
{surface_todos}
 *
 * Do not run against external URLs without completing
 * docs/SCAFFOLD_REVIEW_CHECKLIST.md.
 */

test.describe('Regression Suite', () => {{
  test.skip(true, 'Regression suite — build after smoke suite is stable and approved.');

  test('regression placeholder', async ({{ page }}) => {{
    // TODO: Add regression tests based on confirmed application flows.
    // Reference: docs/TEST_STRATEGY.md for recommended coverage areas.
  }});
}});
"""

    def _gen_checkout_spec(self) -> str:
        return """import { test, expect } from '@playwright/test';

/**
 * Checkout / payment flow placeholder.
 *
 * BLOCKED: Payment testing requires written sandbox confirmation.
 * Do NOT run payment flow tests without:
 * 1. Written client confirmation that payment provider is in sandbox/test mode.
 * 2. Test card numbers confirmed (e.g. Stripe test cards).
 * 3. No real money involved — ever.
 *
 * See docs/SCAFFOLD_REVIEW_CHECKLIST.md and SAFETY_RULES.md Rule 5.
 */

test.describe('Checkout Suite [BLOCKED — sandbox approval required]', () => {
  test.skip(true, 'Payment testing blocked until sandbox confirmation is obtained in writing.');

  test('checkout with test card completes', async ({ page }) => {
    // TODO: Implement only after written sandbox confirmation.
    // Use Stripe test cards or equivalent — NEVER real card numbers.
  });
});
"""

    def _gen_admin_spec(self) -> str:
        return """import { test, expect } from '@playwright/test';

/**
 * Admin panel placeholder.
 *
 * BLOCKED: Admin panel testing requires:
 * 1. Admin test account approval.
 * 2. Explicit written confirmation that destructive admin actions are in scope.
 * 3. No production admin access without explicit read-only approval.
 *
 * See docs/SCAFFOLD_REVIEW_CHECKLIST.md.
 */

test.describe('Admin Suite [BLOCKED — admin approval required]', () => {
  test.skip(true, 'Admin tests blocked until admin test account is approved.');

  test('admin can view user list', async ({ page }) => {
    // TODO: Implement after admin account approval.
    // Use synthetic admin test account only — never real admin credentials.
  });

  test('destructive admin actions are out of scope by default', async ({ page }) => {
    // Destructive actions (delete user, bulk delete, etc.) require separate
    // explicit written approval. Do not implement without that approval.
    test.skip(true, 'Destructive admin actions require explicit scope confirmation.');
  });
});
"""

    def _gen_base_page(self) -> str:
        return """import { Page, Locator, expect } from '@playwright/test';

/**
 * BasePage — shared helpers for all page objects.
 * Extend this class for each page/component under test.
 */
export class BasePage {
  readonly page: Page;

  constructor(page: Page) {
    this.page = page;
  }

  async navigate(path: string = '/'): Promise<void> {
    // baseURL is set from process.env.BASE_URL in playwright.config.ts.
    // Do not hardcode target URLs here.
    await this.page.goto(path);
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('networkidle');
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }

  async takeScreenshot(name: string): Promise<void> {
    await this.page.screenshot({ path: `test-results/screenshots/${name}.png` });
  }

  async clickAndWait(locator: Locator): Promise<void> {
    await locator.click();
    await this.page.waitForLoadState('networkidle');
  }
}
"""

    def _gen_login_page(self) -> str:
        return """import { Page } from '@playwright/test';
import { BasePage } from './BasePage';

/**
 * LoginPage — page object for the login/auth flow.
 *
 * IMPORTANT: Selectors are placeholders. Replace with actual application selectors
 * after inspecting the real application. Do not guess production selectors.
 *
 * Credential use requires explicit approval. Use TEST_USERNAME / TEST_PASSWORD
 * from .env — synthetic test accounts only, never real user accounts.
 */
export class LoginPage extends BasePage {
  // TODO: Replace these selectors with actual application selectors.
  private readonly emailInput  = this.page.locator('[data-testid="email"]');
  private readonly passwordInput = this.page.locator('[data-testid="password"]');
  private readonly submitButton  = this.page.locator('[data-testid="submit"]');
  private readonly errorMessage  = this.page.locator('[data-testid="error"]');

  constructor(page: Page) {
    super(page);
  }

  async goto(): Promise<void> {
    // TODO: Confirm login path after inspecting the real application.
    await this.navigate('/login');
  }

  async login(username: string, password: string): Promise<void> {
    // Credentials must come from approved env vars — never hardcoded.
    await this.emailInput.fill(username);
    await this.passwordInput.fill(password);
    await this.submitButton.click();
  }

  async getErrorMessage(): Promise<string | null> {
    if (await this.errorMessage.isVisible()) {
      return this.errorMessage.textContent();
    }
    return null;
  }
}
"""

    def _gen_dashboard_page(self) -> str:
        return """import { Page } from '@playwright/test';
import { BasePage } from './BasePage';

/**
 * DashboardPage — page object for the main dashboard/home.
 *
 * IMPORTANT: Selectors are placeholders. Replace after inspecting the real application.
 */
export class DashboardPage extends BasePage {
  // TODO: Replace these selectors with actual application selectors.
  private readonly pageHeading  = this.page.locator('h1');
  private readonly navMenu      = this.page.locator('nav');
  private readonly userAvatar   = this.page.locator('[data-testid="user-avatar"]');

  constructor(page: Page) {
    super(page);
  }

  async goto(): Promise<void> {
    // TODO: Confirm dashboard path after inspecting the real application.
    await this.navigate('/dashboard');
  }

  async isLoaded(): Promise<boolean> {
    return this.pageHeading.isVisible();
  }

  async getHeading(): Promise<string | null> {
    return this.pageHeading.textContent();
  }
}
"""

    def _gen_fixtures(self, blueprint: ProjectBlueprint) -> str:
        pt = blueprint.project_type
        auth_fixture = ""
        if pt in ("web_saas", "auth_heavy", "ecommerce", "admin_panel", "mixed_ui_api"):
            auth_fixture = """
// Authenticated page fixture — requires approved test credentials.
// Set TEST_USERNAME and TEST_PASSWORD in .env after approval.
export const authTest = test.extend<{ authenticatedPage: Page }>({
  authenticatedPage: async ({ page }, use) => {
    // TODO: Implement login steps using LoginPage after selectors are confirmed.
    // const loginPage = new LoginPage(page);
    // await loginPage.goto();
    // await loginPage.login(getEnv('TEST_USERNAME'), getEnv('TEST_PASSWORD'));
    await use(page);
  },
});
"""
        return f"""import {{ test, Page }} from '@playwright/test';
import {{ getEnv }} from '../utils/env';

/**
 * Test fixtures — {blueprint.project_id}
 *
 * Extend with project-specific fixtures as the scaffold is customised.
 */

// Base fixture — re-export standard test for consistent imports.
export {{ test, expect }} from '@playwright/test';
{auth_fixture}
"""

    def _gen_env_util(self) -> str:
        return """/**
 * env.ts — safe environment variable reader.
 *
 * Throws a clear error if a required variable is missing,
 * rather than silently using undefined.
 *
 * Never hardcode secrets, URLs, or credentials in this file.
 * All values must come from .env (excluded from git).
 */

export function getEnv(key: string, fallback?: string): string {
  const value = process.env[key];
  if (value !== undefined && value !== '') {
    return value;
  }
  if (fallback !== undefined) {
    return fallback;
  }
  throw new Error(
    `Required environment variable "${key}" is not set. ` +
    'Copy .env.example to .env and set the value after obtaining approval.'
  );
}

export function getBaseUrl(): string {
  // BASE_URL must be explicitly approved before use.
  // 'http://localhost:3000' is a placeholder only — not a real test target.
  return process.env.BASE_URL || 'http://localhost:3000';
}

export function getApiBaseUrl(): string {
  return process.env.API_BASE_URL || 'http://localhost:3001';
}
"""

    def _gen_test_data_util(self, blueprint: ProjectBlueprint) -> str:
        return f"""/**
 * test-data.ts — test data factory for {blueprint.project_id}.
 *
 * IMPORTANT: Never hardcode real credentials, real emails, or real card numbers.
 * All test data must be synthetic. Real credentials belong in .env only.
 *
 * Use this factory to generate repeatable, safe test data.
 */

export interface TestUser {{
  email: string;
  password: string;
  role: string;
}}

export interface TestApiPayload {{
  [key: string]: unknown;
}}

/**
 * Get test user credentials from environment variables.
 * Requires TEST_USERNAME and TEST_PASSWORD to be set after approval.
 */
export function getTestUser(role: string = 'standard'): TestUser {{
  return {{
    email:    process.env.TEST_USERNAME || 'test-user@example.com',
    password: process.env.TEST_PASSWORD || 'PLACEHOLDER_DO_NOT_USE',
    role,
  }};
}}

/**
 * Generate a unique test identifier to avoid data collisions between runs.
 */
export function uniqueId(prefix: string = 'test'): string {{
  return `${{prefix}}-${{Date.now()}}-${{Math.random().toString(36).slice(2, 7)}}`;
}}

/**
 * Generate a safe test email that is clearly synthetic.
 */
export function testEmail(prefix: string = 'qa'): string {{
  return `${{prefix}}+${{uniqueId()}}@example.com`;
}}
"""

    def _gen_api_client(self) -> str:
        return """import { APIRequestContext } from '@playwright/test';
import { getApiBaseUrl } from './env';

/**
 * api-client.ts — Playwright request context wrapper.
 *
 * IMPORTANT: API_BASE_URL must be set and approved before use.
 * No real API calls are made at scaffold generation time.
 *
 * Use Playwright's built-in request fixture for API testing.
 * See tests/api/api-placeholder.spec.ts for examples.
 */

export class ApiClient {
  private readonly request: APIRequestContext;
  private readonly baseUrl: string;

  constructor(request: APIRequestContext) {
    this.request = request;
    this.baseUrl = getApiBaseUrl();
  }

  async get(path: string, options?: { headers?: Record<string, string> }) {
    return this.request.get(`${this.baseUrl}${path}`, options);
  }

  async post(path: string, data: unknown, options?: { headers?: Record<string, string> }) {
    return this.request.post(`${this.baseUrl}${path}`, {
      data,
      ...options,
    });
  }

  async withAuthHeader(token: string): Promise<{ Authorization: string }> {
    // Token must come from approved env var — never hardcoded.
    return { Authorization: `Bearer ${token}` };
  }
}
"""

    def _gen_test_data_readme(self) -> str:
        return """# Test Data — Governance

> **No real credentials, real emails, or real card numbers belong in this directory.**

---

## Rules

1. **All test data is synthetic.** Real user data must never appear in test files.
2. **Credentials live in `.env` only.** `.env` is gitignored and must never be committed.
3. **Sample files use `example.json` suffix.** These are templates — not real data.
4. **Payment test data requires sandbox confirmation.** Never use real card numbers.

## What belongs here

- Sample request/response payload structures (no real values)
- Fixture schema definitions (shapes, not real data)
- Test data README and governance notes

## What does NOT belong here

- Real passwords, API keys, tokens, or session values
- Real email addresses
- Real card numbers or payment tokens
- Any file exported from a production system
"""

    def _gen_sample_users(self) -> str:
        data = {
            "_note": "This is a placeholder structure only. No real credentials.",
            "_governance": "Real values must come from .env after approval. Never commit real values.",
            "users": [
                {
                    "id":       "test-user-001",
                    "email":    "test-user@example.com",
                    "role":     "standard",
                    "password": "PLACEHOLDER — set TEST_PASSWORD in .env after approval",
                },
                {
                    "id":       "test-admin-001",
                    "email":    "test-admin@example.com",
                    "role":     "admin",
                    "password": "PLACEHOLDER — set TEST_ADMIN_PASSWORD in .env after approval",
                },
            ],
        }
        return json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    def _gen_test_strategy_doc(
        self, blueprint: ProjectBlueprint, strategy: Optional[QAStrategy]
    ) -> str:
        pt = blueprint.project_type
        env = blueprint.environment or "unknown"

        if strategy:
            rec_layers = [tl.layer for tl in strategy.test_layers if tl.recommended and not tl.blocked]
            def_layers = [tl.layer for tl in strategy.test_layers if not tl.recommended and not tl.blocked]
            blk_layers = [tl.layer for tl in strategy.test_layers if tl.blocked]
            areas = [f"- {a.name}: {a.description}" for a in strategy.strategy_areas[:6]]
            risk_count = len(strategy.risk_matrix)
            confidence = strategy.confidence_level
        else:
            rec_layers = ["smoke", "ui", "manual_exploratory"]
            def_layers = ["visual", "performance"]
            blk_layers = ["mobile_native"]
            areas = ["- Core user workflows", "- Auth and session management"]
            risk_count = 0
            confidence = "low"

        rec_str = ", ".join(rec_layers) if rec_layers else "smoke, ui"
        def_str = ", ".join(def_layers) if def_layers else "visual, performance"
        blk_str = ", ".join(blk_layers) if blk_layers else "mobile_native"
        areas_str = "\n".join(areas)

        return f"""# Test Strategy — {blueprint.project_id}

> **Planning document only. No tests have been executed.**

---

## Project context

| Field         | Value |
|---|---|
| Project type  | `{pt}` |
| Environment   | `{env}` |
| Confidence    | `{confidence}` |

## Strategy areas

{areas_str}

## Test layer recommendations

**Recommended:** {rec_str}

**Deferred (optional):** {def_str}

**Blocked (require approval):** {blk_str}

## Risk summary

{risk_count} risk items identified. See `QA_STRATEGY.json` in `02_strategy/` for full risk matrix.

## Key constraints

- No execution occurs in Phase 3A — this is scaffold generation only.
- All test execution requires completing `SCAFFOLD_REVIEW_CHECKLIST.md`.
- Credentials require explicit approval before use.
- Payment testing requires sandbox confirmation in writing.
- Mobile native testing is deferred to Phase 3+ (device setup required).

---

_Strategy generated by QAStrategyPlanner (Phase 2C). Scaffold generated by FrameworkScaffoldGenerator (Phase 3A)._
_No tests have been executed. No URLs have been fetched. No credentials have been used._
"""

    def _gen_how_to_run(self, blueprint: ProjectBlueprint) -> str:
        return f"""# How to Run — {blueprint.project_id}

> **Complete SCAFFOLD_REVIEW_CHECKLIST.md before running anything.**

---

## Step 1 — Install dependencies

```bash
cd outputs/{blueprint.project_id}/03_framework/playwright
npm install
npx playwright install
```

Do not run `npm install` before completing the review checklist.

---

## Step 2 — Configure environment

```bash
cp .env.example .env
```

Edit `.env` and set:
- `BASE_URL` — approved test target URL (staging, not production)
- `TEST_USERNAME` — synthetic test account email
- `TEST_PASSWORD` — synthetic test account password

**Never commit `.env` files.** They are gitignored.

---

## Step 3 — TypeScript check (safe — no execution)

```bash
npm run typecheck
```

This compiles TypeScript without running tests. Safe to run anytime.

---

## Step 4 — Run smoke tests (requires approval)

```bash
npm run test:smoke
```

Requires:
- `BASE_URL` set and approved
- Approval checklist completed
- Staging environment confirmed

---

## Step 5 — View report

```bash
npm run report
```

---

## Approval checklist before any execution

See `SCAFFOLD_REVIEW_CHECKLIST.md` for the full checklist.

Key gates:
- [ ] Target URL explicitly approved
- [ ] Environment confirmed as staging (not production)
- [ ] Test credentials are synthetic test accounts
- [ ] Payment flows confirmed in sandbox mode
- [ ] Admin/destructive actions explicitly scoped and approved

---

_No external URLs have been fetched. No credentials have been used. This guide is informational only until approval is obtained._
"""

    def _gen_review_checklist(
        self, blueprint: ProjectBlueprint, strategy: Optional[QAStrategy]
    ) -> str:
        pt = blueprint.project_type
        payment_item = ""
        admin_item = ""
        if pt == "ecommerce":
            payment_item = "- [ ] Payment provider confirmed in sandbox/test mode (written confirmation from client)\n- [ ] Test card numbers confirmed (e.g. Stripe test cards) — no real card numbers\n"
        if pt == "admin_panel":
            admin_item = "- [ ] Admin test account is synthetic and approved — not a real admin account\n- [ ] Destructive admin actions are explicitly scoped or out of scope\n"

        return f"""# Scaffold Review Checklist — {blueprint.project_id}

> **Complete all items before running any test command or connecting to any external URL.**

---

## Security and secrets

- [ ] No raw passwords, API keys, or tokens are hardcoded in any generated file
- [ ] `.env` is gitignored — confirmed `.gitignore` includes `.env`
- [ ] `.env.example` contains placeholder values only
- [ ] `sample-users.example.json` contains no real email addresses or passwords
- [ ] All credential references use `process.env.*` — not hardcoded strings

---

## Target environment

- [ ] `BASE_URL` in `.env` is set to an approved staging URL — not production
- [ ] Target environment confirmed as staging (separated from production)
- [ ] Production testing requires explicit written read-only approval — not granted by default
- [ ] `API_BASE_URL` (if used) is set to an approved API target

---

## Credentials and test accounts

- [ ] `TEST_USERNAME` and `TEST_PASSWORD` refer to synthetic test accounts — not real users
- [ ] Test accounts created specifically for testing — not shared with real users
- [ ] No production credentials are used anywhere
{payment_item}{admin_item}
---

## Framework structure

- [ ] Selectors in `pages/` have been reviewed — placeholder selectors replaced with real ones
- [ ] Smoke spec `smoke.spec.ts` has a real page title assertion (not just `/.+/`)
- [ ] Auth spec (if applicable) has real login selectors — not placeholder `[data-testid="email"]`
- [ ] API spec (if applicable) has correct endpoint paths — not just `/health`
- [ ] Regression spec has real test cases — not just `test.skip` placeholders

---

## Approval gates

- [ ] This checklist is complete — signed off by senior QA reviewer
- [ ] Target URL execution approved — approval recorded
- [ ] Client is aware tests will run against their environment
- [ ] No client-facing report will be delivered without separate human review

---

## Delivery

- [ ] `client_ready` is `False` in `FRAMEWORK_SCAFFOLD.json` — confirmed not delivered to client
- [ ] Client delivery requires completing `HUMAN_REVIEW_REQUIRED.md` — not yet done

---

**Sign-off:** _______________ **Date:** _______________

_This checklist must be completed by a senior QA reviewer. Do not run any tests without this sign-off._
"""

    # ------------------------------------------------------------------
    # Metadata writers
    # ------------------------------------------------------------------

    def _write_scaffold_metadata(self, scaffold: FrameworkScaffold, out_dir: Path) -> None:
        json_path = out_dir / "FRAMEWORK_SCAFFOLD.json"
        json_path.write_text(
            json.dumps(scaffold.to_dict(), indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        md_path = out_dir / "FRAMEWORK_SCAFFOLD.md"
        md_path.write_text(self._gen_framework_scaffold_md(scaffold), encoding="utf-8")

    def _gen_framework_scaffold_md(self, scaffold: FrameworkScaffold) -> str:
        file_rows = "\n".join(
            f"| `{f.path}` | {f.file_type} | {f.purpose} |"
            for f in scaffold.files
        )
        return f"""# Framework Scaffold — {scaffold.project_id}

> **Generated scaffold — not yet executed. Review required before running.**

---

## Summary

| Field              | Value |
|---|---|
| Project ID         | `{scaffold.project_id}` |
| Framework type     | `{scaffold.framework_type}` |
| Language           | `{scaffold.language}` |
| Test runner        | `{scaffold.test_runner}` |
| Scaffold status    | `{scaffold.scaffold_status}` |
| Client visible     | `{scaffold.client_visible}` |
| Requires review    | `{scaffold.requires_review}` |
| Execution allowed  | `{scaffold.execution_allowed}` |
| Generated from     | {', '.join(scaffold.generated_from)} |
| Generated at       | {scaffold.created_at} |

## Files generated ({len(scaffold.files)})

| Path | Type | Purpose |
|---|---|---|
{file_rows}

## Safety notes

{chr(10).join('- ' + n for n in scaffold.notes)}

---

_Generated by FrameworkScaffoldGenerator (Phase 3A). No tests have been executed._
_Complete docs/SCAFFOLD_REVIEW_CHECKLIST.md before any local validation._
"""
