"""Phase 5N — Passive security runner.

Default mode: generates Playwright request-based header check skeleton (no network calls).
Approved execution mode: performs real HTTP HEAD request and checks OWASP headers.

Safety invariants always enforced:
- Passive / read-only HEAD requests only
- No active security scan
- No fuzzing or exploit attempts
- No auth bypass
- No destructive actions
- human_review_required=True
"""
from __future__ import annotations

import json
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

from core.schemas.passive_security import (
    HEADER_GUIDANCE,
    OWASP_SECURITY_HEADERS,
    PassiveSecurityReport,
    SecurityHeaderCheck,
)

_SPEC_TEMPLATE = """\
// AUTO-GENERATED by AI QA Factory — Phase 5N Passive Security
// Target:  {target_url}
// Status:  planning_only — human review required before executing
//
// Checks: OWASP recommended security headers (passive / read-only)
// No exploit attempts, no active scanning, no auth bypass.
//
// Run with:
//   npx playwright test {spec_filename} --grep @passive-security

import {{ test, expect }} from '@playwright/test';

const TARGET_URL = '{target_url}';

test.describe('Passive Security Headers @passive-security', () => {{
{test_blocks}
}});
"""

_HEADER_TEST = """\
  test('{header_display} header present @passive-security @smoke', async ({{ request }}) => {{
    const response = await request.head(TARGET_URL);
    const value = response.headers()['{header_name}'];
    // {guidance}
    expect(value).toBeTruthy();
  }});
"""

_HEADER_DISPLAY = {
    "strict-transport-security": "HSTS",
    "content-security-policy": "CSP",
    "x-content-type-options": "X-Content-Type-Options",
    "x-frame-options": "X-Frame-Options",
    "referrer-policy": "Referrer-Policy",
}

_QA_USER_AGENT = "AI-QA-Factory/5N PassiveSecurity (+read-only)"


def _fetch_response_headers(url: str) -> dict[str, str]:
    """Perform a single passive HEAD request. No auth, no exploit, read-only."""
    req = urllib.request.Request(url, method="HEAD")
    req.add_header("User-Agent", _QA_USER_AGENT)
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:  # noqa: S310
            return {k.lower(): v for k, v in resp.headers.items()}
    except urllib.error.URLError as exc:
        raise RuntimeError(f"HEAD request failed for {url}: {exc}") from exc


class PassiveSecurityRunner:
    """Generates passive security plans and optionally runs read-only header checks."""

    def __init__(
        self,
        project_id: str,
        target_url: str,
        outputs_root: str = "outputs",
    ) -> None:
        self.project_id = project_id
        self.target_url = target_url
        self.outputs_root = Path(outputs_root)
        self._out_dir = self.outputs_root / project_id / "31_passive_security"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_plan(self, write_files: bool = True) -> PassiveSecurityReport:
        """Generate Playwright skeleton spec + planning report. No network calls."""
        spec_filename = "passive_security.generated.spec.ts"
        checks = [
            SecurityHeaderCheck(
                header_name=h,
                present=False,
                value="",
                guidance=HEADER_GUIDANCE.get(h, ""),
                check_status="not_checked",
            )
            for h in OWASP_SECURITY_HEADERS
        ]
        report = PassiveSecurityReport(
            project_id=self.project_id,
            generated_at=datetime.now(timezone.utc).isoformat(),
            target_url=self.target_url,
            headers_checked=checks,
            total_headers_checked=0,
            missing_headers=0,
            status="planning_only",
            notes=[
                "Skeleton spec generated — no network calls performed.",
                f"Headers planned: {len(OWASP_SECURITY_HEADERS)} OWASP checks.",
                "Approved execution performs a passive HEAD request (read-only).",
                "Requires human review before client delivery.",
            ],
        )
        spec_content = self._generate_spec(spec_filename)
        if write_files:
            self._out_dir.mkdir(parents=True, exist_ok=True)
            spec_path = self._out_dir / spec_filename
            spec_path.write_text(spec_content, encoding="utf-8")
            report.generated_test_file = str(spec_path)
            (self._out_dir / "passive_security_report.json").write_text(
                json.dumps(report.to_dict(), indent=2, default=str), encoding="utf-8"
            )
            (self._out_dir / "passive_security_summary.md").write_text(
                self._generate_summary(report), encoding="utf-8"
            )
            (self._out_dir / "security_headers.json").write_text(
                json.dumps({"note": "Populated after execution.", "headers": {}}, indent=2),
                encoding="utf-8",
            )
        return report

    def execute(
        self,
        approve_public_readonly: bool = False,
        write_files: bool = True,
    ) -> PassiveSecurityReport:
        """Approved execution path — performs a passive HEAD request.

        Requires --approve-public-readonly-execution. Checks presence of
        OWASP security headers. No active scan, no exploit, no auth bypass.
        """
        if not approve_public_readonly:
            raise ValueError(
                "Passive security execution requires --approve-public-readonly-execution."
            )
        raw_headers = _fetch_response_headers(self.target_url)
        checks: list[SecurityHeaderCheck] = []
        found: list[str] = []
        missing: list[str] = []
        for h in OWASP_SECURITY_HEADERS:
            value = raw_headers.get(h, "")
            present = bool(value)
            status = "present" if present else "missing"
            checks.append(
                SecurityHeaderCheck(
                    header_name=h,
                    present=present,
                    value=value,
                    guidance=HEADER_GUIDANCE.get(h, ""),
                    check_status=status,
                )
            )
            if present:
                found.append(h)
            else:
                missing.append(h)

        spec_filename = "passive_security.generated.spec.ts"
        report = PassiveSecurityReport(
            project_id=self.project_id,
            generated_at=datetime.now(timezone.utc).isoformat(),
            target_url=self.target_url,
            headers_checked=checks,
            total_headers_checked=len(checks),
            missing_headers=len(missing),
            status="executed",
            headers_found=found,
            headers_missing=missing,
            notes=[
                f"HEAD request performed against {self.target_url}.",
                f"Headers present: {len(found)}/{len(OWASP_SECURITY_HEADERS)}.",
                f"Headers missing: {missing}" if missing else "All checked headers present.",
                "Human review required before client delivery.",
            ],
        )
        if write_files:
            self._out_dir.mkdir(parents=True, exist_ok=True)
            spec_path = self._out_dir / spec_filename
            spec_path.write_text(self._generate_spec(spec_filename), encoding="utf-8")
            report.generated_test_file = str(spec_path)
            (self._out_dir / "passive_security_report.json").write_text(
                json.dumps(report.to_dict(), indent=2, default=str), encoding="utf-8"
            )
            (self._out_dir / "passive_security_summary.md").write_text(
                self._generate_summary(report), encoding="utf-8"
            )
            (self._out_dir / "security_headers.json").write_text(
                json.dumps({"headers": raw_headers}, indent=2), encoding="utf-8"
            )
        return report

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _generate_spec(self, spec_filename: str) -> str:
        test_blocks = ""
        for h in OWASP_SECURITY_HEADERS:
            display = _HEADER_DISPLAY.get(h, h)
            guidance = HEADER_GUIDANCE.get(h, "")
            test_blocks += _HEADER_TEST.format(
                header_name=h, header_display=display, guidance=guidance
            )
        return _SPEC_TEMPLATE.format(
            target_url=self.target_url,
            spec_filename=spec_filename,
            test_blocks=test_blocks,
        )

    def _generate_summary(self, report: PassiveSecurityReport) -> str:
        lines = [
            f"# Passive Security Summary — {report.project_id}",
            "",
            f"**Status:** {report.status}",
            f"**Target:** {report.target_url}",
            f"**Generated:** {report.generated_at}",
            "",
            "## Security Header Results",
            "",
            "| Header | Status | Guidance |",
            "|--------|--------|---------|",
        ]
        for check in report.headers_checked:
            icon = "✓" if check.check_status == "present" else ("✗" if check.check_status == "missing" else "–")
            lines.append(
                f"| {check.header_name} | {icon} {check.check_status} | {check.guidance} |"
            )
        lines += [
            "",
            "## Notes",
            "",
        ]
        for note in report.notes:
            lines.append(f"- {note}")
        if report.status == "planning_only":
            lines += [
                "",
                "> **DRAFT** — Generated checks only; execution requires approval.",
            ]
        else:
            lines += [
                "",
                f"> **Executed** — {report.total_headers_checked} headers checked, "
                f"{report.missing_headers} missing.",
            ]
        lines.append("> Human review required before client delivery.")
        return "\n".join(lines) + "\n"
