"""Phase 5N — Performance smoke runner.

Default mode: generates Playwright CDP timing skeleton spec (no network calls).
Approved execution mode: same skeleton plus run instructions (requires dual approval).

Safety invariants always enforced:
- No load testing
- No active scan
- No production writes
- Passive / read-only timing observation only
- human_review_required=True
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from core.schemas.performance_smoke import (
    DEFAULT_THRESHOLDS,
    PERFORMANCE_METRICS,
    PerformanceThreshold,
    PerformanceSmokeReport,
)

_SPEC_TEMPLATE = """\
// AUTO-GENERATED by AI QA Factory — Phase 5N Performance Smoke
// Target:  {target_url}
// Status:  planning_only — human review required before executing
//
// Thresholds (Core Web Vitals):
{threshold_comments}//
// Run with:
//   npx playwright test {spec_filename} --grep @performance

import {{ test, expect }} from '@playwright/test';

const TARGET_URL = '{target_url}';

// Thresholds in milliseconds
{threshold_consts}

test.describe('Performance Smoke @performance', () => {{
  test('page loads within LCP threshold @performance @smoke', async ({{ page }}) => {{
    await page.goto(TARGET_URL, {{ waitUntil: 'domcontentloaded' }});
    const lcp = await page.evaluate(
      () =>
        new Promise<number>(resolve => {{
          const observer = new PerformanceObserver(list => {{
            const entries = list.getEntries();
            resolve(entries[entries.length - 1].startTime);
          }});
          observer.observe({{ type: 'largest-contentful-paint', buffered: true }});
          setTimeout(() => resolve(0), 5000);
        }})
    );
    expect(lcp).toBeLessThan(LCP_THRESHOLD_MS);
  }});

  test('first contentful paint within FCP threshold @performance @smoke', async ({{ page }}) => {{
    await page.goto(TARGET_URL, {{ waitUntil: 'domcontentloaded' }});
    const fcp = await page.evaluate(() => {{
      const entry = performance.getEntriesByName('first-contentful-paint')[0];
      return entry ? entry.startTime : 0;
    }});
    expect(fcp).toBeLessThan(FCP_THRESHOLD_MS);
  }});

  test('TTFB within threshold @performance @smoke', async ({{ page }}) => {{
    await page.goto(TARGET_URL, {{ waitUntil: 'domcontentloaded' }});
    const ttfb = await page.evaluate(() => {{
      const nav = performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming;
      return nav ? nav.responseStart - nav.requestStart : 0;
    }});
    expect(ttfb).toBeLessThan(TTFB_THRESHOLD_MS);
  }});

{endpoint_tests}
}});
"""

_ENDPOINT_TEST = """\
  test('endpoint load time: {path} @performance', async ({{ page }}) => {{
    const start = Date.now();
    await page.goto('{url}', {{ waitUntil: 'domcontentloaded' }});
    const elapsed = Date.now() - start;
    expect(elapsed).toBeLessThan(LCP_THRESHOLD_MS);
  }});
"""


class PerformanceSmokeRunner:
    """Generates performance smoke plans and Playwright CDP timing skeletons."""

    def __init__(
        self,
        project_id: str,
        target_url: str,
        outputs_root: str = "outputs",
        endpoints_to_measure: list[str] | None = None,
    ) -> None:
        self.project_id = project_id
        self.target_url = target_url.rstrip("/")
        self.outputs_root = Path(outputs_root)
        self.endpoints_to_measure: list[str] = endpoints_to_measure or ["/"]
        self._out_dir = self.outputs_root / project_id / "30_performance"

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_plan(self, write_files: bool = True) -> PerformanceSmokeReport:
        """Generate Playwright skeleton spec + planning report. No network calls."""
        spec_filename = "performance_smoke.generated.spec.ts"
        thresholds = [
            PerformanceThreshold(
                metric=m,
                threshold_ms=DEFAULT_THRESHOLDS[m],
                guidance=f"{m} should be under {DEFAULT_THRESHOLDS[m]}ms (Core Web Vitals).",
            )
            for m in PERFORMANCE_METRICS
        ]
        report = PerformanceSmokeReport(
            project_id=self.project_id,
            generated_at=datetime.now(timezone.utc).isoformat(),
            target_url=self.target_url,
            thresholds=thresholds,
            endpoints_to_measure=self.endpoints_to_measure,
            status="planning_only",
            notes=[
                "Skeleton spec generated — no execution performed.",
                f"Endpoints planned: {len(self.endpoints_to_measure)}.",
                "Thresholds: LCP<2500ms, FCP<1800ms, TTFB<800ms (Core Web Vitals).",
                "Requires human review and explicit approval before execution.",
                "Run with: npx playwright test --grep @performance",
            ],
        )
        spec_content = self._generate_spec(spec_filename)
        if write_files:
            self._out_dir.mkdir(parents=True, exist_ok=True)
            spec_path = self._out_dir / spec_filename
            spec_path.write_text(spec_content, encoding="utf-8")
            report.generated_test_file = str(spec_path)
            (self._out_dir / "performance_report.json").write_text(
                json.dumps(report.to_dict(), indent=2, default=str), encoding="utf-8"
            )
            (self._out_dir / "performance_summary.md").write_text(
                self._generate_summary(report), encoding="utf-8"
            )
            (self._out_dir / "slow_resources.json").write_text(
                json.dumps({"note": "Populated after execution.", "slow_resources": []}, indent=2),
                encoding="utf-8",
            )
        return report

    def execute(
        self,
        approve_public_readonly: bool = False,
        approve_browser_execution: bool = False,
        write_files: bool = True,
    ) -> PerformanceSmokeReport:
        """Approved execution path — requires both approval flags.

        Generates the execution-ready skeleton and annotates the report.
        Actual CDP timing measurement runs via:
          npx playwright test <spec_file> --grep @performance
        """
        if not approve_public_readonly:
            raise ValueError(
                "Performance execution requires --approve-public-readonly-execution."
            )
        if not approve_browser_execution:
            raise ValueError(
                "Performance execution requires --approve-browser-execution."
            )
        report = self.generate_plan(write_files=write_files)
        spec_filename = "performance_smoke.generated.spec.ts"
        report.notes.append("Execution approved. Spec is ready to run.")
        report.notes.append(
            f"Run: npx playwright test {spec_filename} --grep @performance"
        )
        report.notes.append(
            "slow_resources.json will be populated after execution."
        )
        return report

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _generate_spec(self, spec_filename: str) -> str:
        threshold_comments = "".join(
            f"//   {m}: < {DEFAULT_THRESHOLDS[m]}ms\n" for m in PERFORMANCE_METRICS
        )
        threshold_consts = "\n".join(
            f"const {m}_THRESHOLD_MS = {DEFAULT_THRESHOLDS[m]};"
            for m in ("LCP", "FCP", "TTFB")
        )
        endpoint_tests = ""
        for path in self.endpoints_to_measure:
            if path == "/":
                continue
            url = f"{self.target_url}{path}"
            endpoint_tests += _ENDPOINT_TEST.format(path=path, url=url)
        return _SPEC_TEMPLATE.format(
            target_url=self.target_url,
            spec_filename=spec_filename,
            threshold_comments=threshold_comments,
            threshold_consts=threshold_consts,
            endpoint_tests=endpoint_tests,
        )

    def _generate_summary(self, report: PerformanceSmokeReport) -> str:
        lines = [
            f"# Performance Smoke Summary — {report.project_id}",
            "",
            f"**Status:** {report.status}",
            f"**Target:** {report.target_url}",
            f"**Generated:** {report.generated_at}",
            "",
            "## Thresholds (Core Web Vitals)",
            "",
            "| Metric | Threshold (ms) | Guidance |",
            "|--------|----------------|---------|",
        ]
        for t in report.thresholds:
            lines.append(f"| {t.metric} | {t.threshold_ms} | {t.guidance} |")
        lines += [
            "",
            "## Endpoints Planned",
            "",
        ]
        for ep in report.endpoints_to_measure:
            lines.append(f"- {ep}")
        lines += [
            "",
            "## Notes",
            "",
        ]
        for note in report.notes:
            lines.append(f"- {note}")
        lines += [
            "",
            "> **DRAFT** — Generated checks only; execution requires approval.",
            "> Human review required before client delivery.",
        ]
        return "\n".join(lines) + "\n"
