"""
Phase 5F — QA Evidence Report Generator.

Safety contract:
- Read-only: reads existing JSON artifacts only.
- No execution: no subprocess, no network calls, no Playwright.
- No .env reading. No .auth reading. No storageState content reading.
- Multi-source: aggregates evidence from multiple source project IDs.
- Secret scan: scans generated report for raw credential/token values
  without printing them.
- safe_to_deliver=False, approved_for_client_delivery=False always.
- human_review_required=True always.
"""
from __future__ import annotations

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from core.schemas.qa_report import (
    QACoverageSummary,
    QAEvidenceItem,
    QAEvidenceReport,
    QAEvidenceSource,
    QASecretScanResult,
)

# Artifact filenames we know how to read
_BROWSER_ARTIFACT = "DEDICATED_AUTH_EXECUTION_REPORT.json"
_API_ARTIFACT = "API_AUTH_EXECUTION_REPORT.json"

# Env var names to check during secret scan (values read at scan time, never logged)
_SECRET_ENV_VAR_NAMES = [
    "ORANGEHRM_USERNAME",
    "ORANGEHRM_PASSWORD",
    "RESTFUL_BOOKER_USERNAME",
    "RESTFUL_BOOKER_PASSWORD",
    "QA_TEST_USERNAME",
    "QA_TEST_PASSWORD",
    "STAGING_USERNAME",
    "STAGING_PASSWORD",
]

# Pattern that might indicate an unmasked API token (long alphanumeric, not [REDACTED])
_TOKEN_PATTERN = re.compile(r'(?<!")\b[a-zA-Z0-9]{20,}\b(?!")')

# Lanes for coverage gap reporting
_ALL_LANES = [
    "browser_auth",
    "api_auth",
    "functional_tests",
    "e2e_scenarios",
    "performance_tests",
    "security_tests",
]


class QAReportGenerator:
    """
    Aggregates existing Phase 5AB / Phase 5E execution artifacts
    into a consolidated QA Evidence Report. No execution performed.
    """

    def __init__(self, outputs_root: Optional[Path] = None) -> None:
        self.outputs_root = outputs_root or Path("outputs")

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(
        self,
        project_id: str,
        source_project_ids: List[str],
        write: bool = True,
    ) -> QAEvidenceReport:
        """Aggregate evidence from source projects and write report."""
        if not source_project_ids:
            source_project_ids = [project_id]

        sources: List[QAEvidenceSource] = []
        for src_id in source_project_ids:
            sources.append(self._read_source(src_id))

        coverage = self._build_coverage(sources)
        now = datetime.now(timezone.utc).isoformat()

        report = QAEvidenceReport(
            project_id=project_id,
            source_project_ids=list(source_project_ids),
            generated_at=now,
            sources=sources,
            coverage=coverage,
            notes=[
                "Generated by QAReportGenerator — read-only, no execution performed.",
                "All source artifacts read from outputs/ directory.",
                "storageState content was never read.",
                "Human review required before any client-facing use.",
            ],
        )

        scan = self._secret_scan(report)
        report.secret_scan = scan

        if write:
            self._write_artifacts(project_id, report)

        return report

    # ------------------------------------------------------------------
    # Source reading
    # ------------------------------------------------------------------

    def _read_source(self, source_project_id: str) -> QAEvidenceSource:
        found: List[str] = []
        missing: List[str] = []
        items: List[QAEvidenceItem] = []

        browser_path = (
            self.outputs_root / source_project_id / "12_dedicated_auth" / _BROWSER_ARTIFACT
        )
        api_path = (
            self.outputs_root / source_project_id / "13_api_auth" / _API_ARTIFACT
        )

        for path, parser in [
            (browser_path, self._parse_browser_artifact),
            (api_path, self._parse_api_artifact),
        ]:
            if path.exists():
                found.append(str(path.relative_to(self.outputs_root)))
                try:
                    item = parser(path, source_project_id)
                    items.append(item)
                except Exception as exc:
                    items.append(QAEvidenceItem(
                        lane="unknown",
                        source_project_id=source_project_id,
                        artifact_path=str(path.relative_to(self.outputs_root)),
                        status="error",
                        notes=[f"Failed to parse artifact: {exc}"],
                    ))
            else:
                missing.append(str(path.relative_to(self.outputs_root)))

        return QAEvidenceSource(
            source_project_id=source_project_id,
            artifacts_found=found,
            artifacts_missing=missing,
            evidence_items=items,
        )

    def _parse_browser_artifact(
        self, path: Path, source_project_id: str
    ) -> QAEvidenceItem:
        data = json.loads(path.read_text(encoding="utf-8"))
        commands = data.get("commands", [])
        total_duration = sum(c.get("duration_seconds", 0) for c in commands)
        artifact_notes = [str(n) for n in data.get("notes", [])]
        return QAEvidenceItem(
            lane="browser_auth",
            target=data.get("target_url", ""),
            target_category=data.get("target_category", ""),
            source_project_id=source_project_id,
            artifact_path=str(path.relative_to(self.outputs_root)),
            status=data.get("execution_status", "unknown"),
            commands_executed=len(commands),
            duration_seconds=round(total_duration, 3),
            notes=[
                "Playwright browser auth via Chromium",
                f"Scenario lane: {data.get('scenario_lane', '')}",
                f"raw_credentials_logged={data.get('raw_credentials_logged', False)}",
            ] + artifact_notes,
        )

    def _parse_api_artifact(
        self, path: Path, source_project_id: str
    ) -> QAEvidenceItem:
        data = json.loads(path.read_text(encoding="utf-8"))
        commands = data.get("commands", [])
        total_duration = sum(c.get("duration_seconds", 0) for c in commands)
        methods = [c.get("method", "") for c in commands]
        return QAEvidenceItem(
            lane="api_auth",
            target=data.get("base_url", ""),
            target_category=data.get("target_profile", ""),
            source_project_id=source_project_id,
            artifact_path=str(path.relative_to(self.outputs_root)),
            status=data.get("execution_status", "unknown"),
            commands_executed=len(commands),
            duration_seconds=round(total_duration, 3),
            notes=[
                f"HTTP API auth — methods: {', '.join(methods)}",
                f"token_logged={data.get('token_logged', False)}",
                f"raw_credentials_logged={data.get('raw_credentials_logged', False)}",
            ],
        )

    # ------------------------------------------------------------------
    # Coverage
    # ------------------------------------------------------------------

    def _build_coverage(self, sources: List[QAEvidenceSource]) -> QACoverageSummary:
        all_items = [item for src in sources for item in src.evidence_items]
        passed = sum(1 for i in all_items if i.status == "passed")
        failed = sum(1 for i in all_items if i.status == "failed")
        missing = sum(1 for i in all_items if i.status == "missing")

        covered_lanes = sorted({i.lane for i in all_items if i.status == "passed"})
        covered_targets = sorted({i.target for i in all_items if i.status == "passed" and i.target})
        not_covered = [lane for lane in _ALL_LANES if lane not in covered_lanes]

        return QACoverageSummary(
            total_evidence_items=len(all_items),
            passed=passed,
            failed=failed,
            missing=missing,
            covered_lanes=covered_lanes,
            covered_targets=covered_targets,
            not_covered=not_covered,
        )

    # ------------------------------------------------------------------
    # Secret scan
    # ------------------------------------------------------------------

    def _secret_scan(self, report: QAEvidenceReport) -> QASecretScanResult:
        """
        Scan generated report content for raw credential/token values.
        Values are read from environment but never printed/logged.
        Returns a scan result with findings described without revealing values.
        """
        # Serialize report to text for scanning (without secret scan field itself)
        report_text = json.dumps({
            "sources": [s.to_dict() for s in report.sources],
            "coverage": report.coverage.to_dict() if report.coverage else {},
            "notes": report.notes,
        }, default=str)

        findings: List[str] = []
        raw_secret_found = False
        raw_token_found = False
        checked: List[str] = []

        # Check known env var values
        for var_name in _SECRET_ENV_VAR_NAMES:
            val = os.environ.get(var_name)
            if val and len(val) >= 3:
                checked.append(var_name)
                if val in report_text:
                    raw_secret_found = True
                    findings.append(
                        f"Raw value of {var_name} found in report content (value not printed)."
                    )

        # Check for long unmasked alphanumeric strings that might be tokens
        # Exclude [REDACTED] and known safe patterns (URLs, file paths, ISO dates)
        safe_prefixes = ("http", "outputs", "2025", "2026", "Phase", "False", "True")
        for match in _TOKEN_PATTERN.finditer(report_text):
            token_candidate = match.group()
            if not any(token_candidate.startswith(p) for p in safe_prefixes):
                if "[REDACTED]" not in report_text[max(0, match.start()-10):match.end()+10]:
                    raw_token_found = True
                    findings.append(
                        f"Possible unmasked token-like value at position {match.start()} "
                        f"(length={len(token_candidate)})."
                    )
                    break  # Report once, don't enumerate all

        verdict = "fail" if (raw_secret_found or raw_token_found) else "clean"
        if findings and not raw_secret_found and not raw_token_found:
            verdict = "warn"

        return QASecretScanResult(
            scan_performed=True,
            raw_secret_found=raw_secret_found,
            raw_token_found=raw_token_found,
            checked_env_var_names=checked,
            findings=findings,
            verdict=verdict,
        )

    # ------------------------------------------------------------------
    # Artifact writing
    # ------------------------------------------------------------------

    def _write_artifacts(self, project_id: str, report: QAEvidenceReport) -> None:
        out = self.outputs_root / project_id / "14_qa_report"
        out.mkdir(parents=True, exist_ok=True)

        # JSON report
        (out / "QA_EVIDENCE_REPORT.json").write_text(
            json.dumps(self._report_to_dict(report), indent=2, default=str),
            encoding="utf-8",
        )

        # MD report
        (out / "QA_EVIDENCE_REPORT.md").write_text(
            self._render_md(report),
            encoding="utf-8",
        )

        # Review checklist
        (out / "QA_REPORT_REVIEW_CHECKLIST.md").write_text(
            self._render_checklist(report),
            encoding="utf-8",
        )

        # Secret scan
        scan = report.secret_scan or QASecretScanResult()
        (out / "QA_REPORT_SECRET_SCAN.json").write_text(
            json.dumps(scan.to_dict(), indent=2, default=str),
            encoding="utf-8",
        )
        (out / "QA_REPORT_SECRET_SCAN.md").write_text(
            self._render_scan_md(scan),
            encoding="utf-8",
        )

    def _report_to_dict(self, report: QAEvidenceReport) -> dict:
        cov = report.coverage
        return {
            "project_id": report.project_id,
            "report_type": report.report_type,
            "source_project_ids": report.source_project_ids,
            "generated_at": report.generated_at,
            "execution_performed": False,
            "network_calls_performed": False,
            "raw_credentials_in_report": False,
            "raw_tokens_in_report": False,
            "storage_state_content_read": False,
            "safe_to_deliver": False,
            "approved_for_client_delivery": False,
            "client_ready": False,
            "human_review_required": True,
            "coverage": cov.to_dict() if cov else {},
            "sources": [
                {
                    "source_project_id": s.source_project_id,
                    "artifacts_found": s.artifacts_found,
                    "artifacts_missing": s.artifacts_missing,
                    "evidence_items": [i.to_dict() for i in s.evidence_items],
                }
                for s in report.sources
            ],
            "secret_scan": report.secret_scan.to_dict() if report.secret_scan else {},
            "notes": report.notes,
        }

    def _render_md(self, report: QAEvidenceReport) -> str:
        cov = report.coverage
        src_ids = ", ".join(report.source_project_ids)
        all_items = [i for s in report.sources for i in s.evidence_items]

        def status_row(item: QAEvidenceItem) -> str:
            sym = "PASS" if item.status == "passed" else (
                "FAIL" if item.status == "failed" else "MISS"
            )
            return (
                f"| {sym} | {item.lane} | {item.target or item.target_category} "
                f"| {item.source_project_id} | {item.commands_executed} | {item.duration_seconds}s |"
            )

        evidence_table = "\n".join(status_row(i) for i in all_items) or "| — | No evidence collected | — | — | — | — |"

        covered_str = "\n".join(f"- {lane}" for lane in (cov.covered_lanes if cov else [])) or "- None"
        not_covered_str = "\n".join(f"- {lane}" for lane in (cov.not_covered if cov else [])) or "- None"
        targets_str = "\n".join(f"- {t}" for t in (cov.covered_targets if cov else [])) or "- None"

        scan = report.secret_scan
        scan_verdict = (scan.verdict if scan else "not performed").upper()
        scan_note = ""
        if scan and scan.findings:
            scan_note = "\n".join(f"- {f}" for f in scan.findings)
        else:
            scan_note = "- No raw credentials or unmasked tokens detected."

        return f"""# QA Evidence Report

**Project:** {report.project_id}
**Sources:** {src_ids}
**Generated:** {report.generated_at}
**Type:** Internal — human review required before any client delivery

---

## Summary

| Lane | Target | Source | Commands | Duration | Status |
|---|---|---|---|---|---|
{evidence_table}

**Passed:** {cov.passed if cov else 0} / {cov.total_evidence_items if cov else 0} evidence items

---

## Browser Auth Evidence (Phase 5AB)

{self._render_lane_section(all_items, "browser_auth")}

---

## API Auth Evidence (Phase 5E)

{self._render_lane_section(all_items, "api_auth")}

---

## Evidence Sources

{self._render_sources_section(report.sources)}

---

## Coverage

**Covered lanes:**
{covered_str}

**Covered targets:**
{targets_str}

**Not yet covered:**
{not_covered_str}

---

## Secret Scan — {scan_verdict}

{scan_note}

---

## Safety Boundary

- execution_performed: False
- network_calls_performed: False
- raw_credentials_in_report: False
- raw_tokens_in_report: False
- storage_state_content_read: False
- safe_to_deliver: **False**
- approved_for_client_delivery: **False**
- client_ready: **False**
- human_review_required: **True**

---

## Human Review Checklist

- [ ] All evidence items reviewed manually.
- [ ] No raw credential or token values visible in this report.
- [ ] Coverage gaps acknowledged and documented.
- [ ] storageState not referenced or included.
- [ ] This report has NOT been sent to the client — `approved_for_client_delivery=False`.

---

## Not Covered / Future Work

{not_covered_str}

These lanes require additional test phases before any coverage claim can be made.
"""

    def _render_lane_section(self, all_items: list, lane: str) -> str:
        items = [i for i in all_items if i.lane == lane]
        if not items:
            return f"No {lane} evidence collected from any source project."
        lines = []
        for item in items:
            lines.append(
                f"**Source:** {item.source_project_id}  \n"
                f"**Target:** {item.target or item.target_category}  \n"
                f"**Status:** {item.status.upper()}  \n"
                f"**Commands:** {item.commands_executed}  \n"
                f"**Duration:** {item.duration_seconds}s  \n"
                f"**Artifact:** `{item.artifact_path}`  \n"
            )
            if item.notes:
                lines.append("**Notes:**\n" + "\n".join(f"- {n}" for n in item.notes))
            lines.append("")
        return "\n".join(lines)

    def _render_sources_section(self, sources: list) -> str:
        lines = []
        for src in sources:
            lines.append(f"### {src.source_project_id}")
            if src.artifacts_found:
                lines.append("**Artifacts found:**")
                lines.extend(f"- `{a}`" for a in src.artifacts_found)
            if src.artifacts_missing:
                lines.append("**Artifacts missing (expected):**")
                lines.extend(f"- `{a}`" for a in src.artifacts_missing)
            lines.append("")
        return "\n".join(lines)

    def _render_checklist(self, report: QAEvidenceReport) -> str:
        src_ids = ", ".join(report.source_project_ids)
        return f"""# QA Report Human Review Checklist

**Project:** {report.project_id}
**Sources:** {src_ids}
**Generated:** {report.generated_at}

## Pre-delivery checklist (all items required before any client delivery)

- [ ] 1. All evidence items verified — status matches actual execution results.
- [ ] 2. No raw credential values appear in QA_EVIDENCE_REPORT.md or .json.
- [ ] 3. No token values appear unmasked in any artifact.
- [ ] 4. Coverage gaps have been reviewed and documented.
- [ ] 5. Secret scan result is CLEAN (see QA_REPORT_SECRET_SCAN.md).
- [ ] 6. storageState content was not included in any report.
- [ ] 7. Report has been reviewed by a human QA engineer.
- [ ] 8. approved_for_client_delivery flag explicitly changed by human (not by system).

**Current state:** `approved_for_client_delivery=False` — DO NOT SEND TO CLIENT.
"""

    def _render_scan_md(self, scan: QASecretScanResult) -> str:
        verdict_label = {"clean": "CLEAN", "warn": "WARN", "fail": "FAIL"}.get(scan.verdict, "UNKNOWN")
        findings_str = "\n".join(f"- {f}" for f in scan.findings) if scan.findings else "- No issues found."
        checked_str = "\n".join(f"- {v}" for v in scan.checked_env_var_names) if scan.checked_env_var_names else "- None set in environment."
        return f"""# QA Report Secret Scan — {verdict_label}

**Verdict:** {verdict_label}
**raw_secret_found:** {scan.raw_secret_found}
**raw_token_found:** {scan.raw_token_found}

## Checked env var names (values never printed)

{checked_str}

## Findings

{findings_str}

Note: env var values were checked internally but never logged, printed, or stored.
"""
