// AUTO-GENERATED by AI QA Factory — Phase 5N Performance Smoke
// Target:  https://demo.example.com
// Status:  planning_only — human review required before executing
//
// Thresholds (Core Web Vitals):
//   LCP: < 2500ms
//   FCP: < 1800ms
//   TTFB: < 800ms
//   TBT: < 300ms
//   CLS: < 100ms
//
// Run with:
//   npx playwright test performance_smoke.generated.spec.ts --grep @performance

import { test, expect } from '@playwright/test';

const TARGET_URL = 'https://demo.example.com';

// Thresholds in milliseconds
const LCP_THRESHOLD_MS = 2500;
const FCP_THRESHOLD_MS = 1800;
const TTFB_THRESHOLD_MS = 800;

test.describe('Performance Smoke @performance', () => {
  test('page loads within LCP threshold @performance @smoke', async ({ page }) => {
    await page.goto(TARGET_URL, { waitUntil: 'domcontentloaded' });
    const lcp = await page.evaluate(
      () =>
        new Promise<number>(resolve => {
          const observer = new PerformanceObserver(list => {
            const entries = list.getEntries();
            resolve(entries[entries.length - 1].startTime);
          });
          observer.observe({ type: 'largest-contentful-paint', buffered: true });
          setTimeout(() => resolve(0), 5000);
        })
    );
    expect(lcp).toBeLessThan(LCP_THRESHOLD_MS);
  });

  test('first contentful paint within FCP threshold @performance @smoke', async ({ page }) => {
    await page.goto(TARGET_URL, { waitUntil: 'domcontentloaded' });
    const fcp = await page.evaluate(() => {
      const entry = performance.getEntriesByName('first-contentful-paint')[0];
      return entry ? entry.startTime : 0;
    });
    expect(fcp).toBeLessThan(FCP_THRESHOLD_MS);
  });

  test('TTFB within threshold @performance @smoke', async ({ page }) => {
    await page.goto(TARGET_URL, { waitUntil: 'domcontentloaded' });
    const ttfb = await page.evaluate(() => {
      const nav = performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming;
      return nav ? nav.responseStart - nav.requestStart : 0;
    });
    expect(ttfb).toBeLessThan(TTFB_THRESHOLD_MS);
  });

  test('endpoint load time: /login @performance', async ({ page }) => {
    const start = Date.now();
    await page.goto('https://demo.example.com/login', { waitUntil: 'domcontentloaded' });
    const elapsed = Date.now() - start;
    expect(elapsed).toBeLessThan(LCP_THRESHOLD_MS);
  });
  test('endpoint load time: /products @performance', async ({ page }) => {
    const start = Date.now();
    await page.goto('https://demo.example.com/products', { waitUntil: 'domcontentloaded' });
    const elapsed = Date.now() - start;
    expect(elapsed).toBeLessThan(LCP_THRESHOLD_MS);
  });

});
