from __future__ import annotations

from typing import Dict
from core.llm_router import LLMRouter
from core.state import QAFactoryState
from core.version import APP_VERSION


class PlaywrightGeneratorAgent:
    name = "Playwright Generator"

    def __init__(self, router: LLMRouter):
        self.router = router

    def run(self, state: QAFactoryState) -> QAFactoryState:
        if state.stack_choice not in {"playwright-ts", "api-first-with-playwright-request"}:
            state.generated_outputs["framework/README.md"] = (
                f"# Automation Scaffold\n\nSelected stack `{state.stack_choice}`. "
                "Playwright TypeScript scaffold skipped or advisory only."
            )
            return state

        notes = self.router.complete(
            "playwright",
            (
                "You are a senior Playwright + TypeScript architect. Return architecture notes only. "
                "Do not output full files. The system creates deterministic TypeScript files separately. "
                "Focus on critical flows, locator strategy, fixtures, CI artifacts, and what must be replaced after MCP/browser analysis."
            ),
            f"""
Client request:
{state.raw_input}

Detected context:
- Project type: {state.project_type}
- Scope: {', '.join(state.automation_scope)}
- Technologies: {', '.join(state.detected_technologies) or 'not specified'}
- Risks: {'; '.join(state.risk_flags)}
- Clarifications: {'; '.join(state.clarifications[:5])}

Return concise architecture notes and priority flows. No code fences.
""",
            max_tokens=1100,
        )
        state.generated_outputs.update(self._deterministic_files(state))
        state.generated_outputs["framework/ARCHITECTURE_NOTES.md"] = notes.text
        state.log(f"{self.name}: deterministic Playwright scaffold generated")
        return state

    def _deterministic_files(self, state: QAFactoryState) -> Dict[str, str]:
        return {
            "framework/README.md": self._readme(state),
            "framework/package.json": self._package_json(),
            "framework/playwright.config.ts": self._playwright_config(),
            "framework/.env.example": self._env_example(),
            "framework/pages/BasePage.ts": self._base_page(),
            "framework/pages/LoginPage.ts": self._login_page(),
            "framework/pages/DashboardPage.ts": self._dashboard_page(),
            "framework/fixtures/test-fixtures.ts": self._fixtures(),
            "framework/utils/apiClient.ts": self._api_client(),
            "framework/tests/ui/smoke.spec.ts": self._ui_smoke(),
            "framework/tests/api/health.spec.ts": self._api_health(),
            "framework/tests/a11y/basic-a11y.spec.ts": self._a11y_smoke(),
            "framework/.github/workflows/playwright.yml": self._github_actions(),
        }

    @staticmethod
    def _readme(state: QAFactoryState) -> str:
        return f"""# Playwright + TypeScript Framework Scaffold

Generated by AI QA Factory v{APP_VERSION}.

**Project type:** {state.project_type}  
**Recommended stack:** {state.stack_choice}  
**Automation scope:** {', '.join(state.automation_scope)}

## Install

```bash
npm install
npx playwright install
cp .env.example .env
npm test
```

## First-run setup

Copy `.env.example` to `.env` and set `BASE_URL` to your staging environment URL.
`BASE_URL` has no default — UI smoke tests will skip and API tests will fail without it.

## Structure

- `pages/` — Page Objects
- `fixtures/` — custom fixtures and auth helpers
- `utils/` — API helper/client utilities
- `tests/ui/` — UI smoke and regression tests
- `tests/api/` — API checks via Playwright request
- `tests/a11y/` — lightweight accessibility checks

## Human review required

Replace placeholder URLs, credentials, locators and business assertions after reviewing the real application or Playwright MCP snapshots.

## Suggested first milestone

{state.client_context.get('recommended_first_milestone', 'Run a short QA audit and automate the most critical smoke flow.')}
"""

    @staticmethod
    def _package_json() -> str:
        return '''{
  "name": "playwright-ts-client-scaffold",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "test": "playwright test",
    "test:ui": "playwright test tests/ui",
    "test:api": "playwright test tests/api",
    "test:a11y": "playwright test tests/a11y",
    "test:headed": "playwright test --headed",
    "report": "playwright show-report",
    "codegen": "playwright codegen"
  },
  "devDependencies": {
    "@playwright/test": "latest",
    "typescript": "latest",
    "dotenv": "latest",
    "@axe-core/playwright": "latest"
  }
}
'''

    @staticmethod
    def _playwright_config() -> str:
        return '''import { defineConfig, devices } from '@playwright/test';
import dotenv from 'dotenv';

dotenv.config();

export default defineConfig({
  testDir: './tests',
  timeout: 30_000,
  expect: { timeout: 10_000 },
  fullyParallel: true,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 2 : undefined,
  reporter: [['list'], ['html'], ['junit', { outputFile: 'test-results/junit.xml' }]],
  use: {
    baseURL: process.env.BASE_URL,
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
  ],
});
'''

    @staticmethod
    def _env_example() -> str:
        return '''BASE_URL=https://example.com
TEST_USER_EMAIL=
TEST_USER_PASSWORD=
API_BASE_URL=https://example.com/api
'''

    @staticmethod
    def _base_page() -> str:
        return '''import { expect, type Locator, type Page } from '@playwright/test';

export abstract class BasePage {
  constructor(protected readonly page: Page) {}

  async goto(path: string): Promise<void> {
    await this.page.goto(path);
    await this.page.waitForLoadState('domcontentloaded');
  }

  async expectVisible(locator: Locator, timeout = 10_000): Promise<void> {
    await expect(locator).toBeVisible({ timeout });
  }

  async expectNoCriticalConsoleErrors(): Promise<void> {
    // TODO: wire console monitoring if the client wants browser error checks.
  }
}
'''

    @staticmethod
    def _login_page() -> str:
        return '''import { expect, type Page } from '@playwright/test';
import { BasePage } from './BasePage';

export class LoginPage extends BasePage {
  readonly email = this.page.getByLabel(/email/i);
  readonly password = this.page.getByLabel(/password/i);
  readonly submit = this.page.getByRole('button', { name: /sign in|log in/i });

  constructor(page: Page) { super(page); }

  async open(): Promise<void> { await this.goto('/login'); }

  async login(email: string, password: string): Promise<void> {
    await this.email.fill(email);
    await this.password.fill(password);
    await this.submit.click();
  }

  async expectLoaded(): Promise<void> { await expect(this.submit).toBeVisible(); }
}
'''

    @staticmethod
    def _dashboard_page() -> str:
        return '''import { expect, type Page } from '@playwright/test';
import { BasePage } from './BasePage';

export class DashboardPage extends BasePage {
  readonly mainRegion = this.page.getByRole('main');

  constructor(page: Page) { super(page); }

  async expectLoaded(): Promise<void> {
    await expect(this.mainRegion).toBeVisible();
  }
}
'''

    @staticmethod
    def _fixtures() -> str:
        return '''import { test as base, expect, type Page } from '@playwright/test';
import { LoginPage } from '../pages/LoginPage';

type Fixtures = { authenticatedPage: Page; };

export const test = base.extend<Fixtures>({
  authenticatedPage: async ({ page }, use) => {
    const email = process.env.TEST_USER_EMAIL;
    const password = process.env.TEST_USER_PASSWORD;
    if (!email || !password) {
      test.skip(true, 'TEST_USER_EMAIL and TEST_USER_PASSWORD are required for authenticated tests');
    }
    const loginPage = new LoginPage(page);
    await loginPage.open();
    await loginPage.login(email!, password!);
    await use(page);
  },
});

export { expect };
'''

    @staticmethod
    def _api_client() -> str:
        return '''import { request, type APIRequestContext } from '@playwright/test';

export async function createApiClient(): Promise<APIRequestContext> {
  return request.newContext({
    baseURL: process.env.API_BASE_URL || 'https://example.com/api',
    extraHTTPHeaders: {
      Accept: 'application/json',
    },
  });
}
'''

    @staticmethod
    def _ui_smoke() -> str:
        return '''import { test, expect } from '@playwright/test';

test.describe('UI smoke checks', () => {
  test('home page loads', async ({ page }) => {
    test.skip(!process.env.BASE_URL, 'Set BASE_URL in .env before running UI smoke tests');
    await page.goto('/');
    // TODO: replace /.+/ with your actual expected title pattern, e.g. /My App/
    await expect(page).toHaveTitle(/.+/);
  });

  test('login page is reachable', async ({ page }) => {
    await page.goto('/login');
    await expect(page.getByRole('button', { name: /sign in|log in/i })).toBeVisible();
  });
});
'''

    @staticmethod
    def _api_health() -> str:
        return '''import { test, expect } from '@playwright/test';
import { createApiClient } from '../../utils/apiClient';

test.describe('API smoke checks', () => {
  test('health endpoint responds', async () => {
    const api = await createApiClient();
    const response = await api.get('/health');
    expect([200, 204]).toContain(response.status());
    await api.dispose();
  });
});
'''

    @staticmethod
    def _a11y_smoke() -> str:
        return '''import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test.describe('Accessibility smoke checks', () => {
  test('home page has no critical accessibility violations', async ({ page }) => {
    await page.goto('/');
    const results = await new AxeBuilder({ page }).analyze();
    const critical = results.violations.filter(v => v.impact === 'critical');
    expect(critical).toEqual([]);
  });
});
'''

    @staticmethod
    def _github_actions() -> str:
        return '''name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx playwright install --with-deps
      - run: npm test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
'''
