"""Phase 5M — Import API Contract CLI.

Parses an OpenAPI/Swagger/Postman spec file and writes a classified
APIContractReport to outputs/<project_id>/25_api_contract/.

Blocked flags: --password, --token, --secret, --api-key, --cookie,
               --pat, --access-token, --bearer, --db-url, --connection-string, --dsn
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_BLOCKED_FLAGS = (
    "--password", "--token", "--secret", "--api-key", "--cookie",
    "--pat", "--access-token", "--bearer", "--db-url",
    "--connection-string", "--dsn",
)

_ARTIFACT_DIR = "25_api_contract"


def _check_blocked_flags(argv: list[str]) -> None:
    for flag in _BLOCKED_FLAGS:
        if flag in argv:
            print(f"[BLOCKED] Flag '{flag}' is not allowed. Exit 2.", file=sys.stderr)
            sys.exit(2)


def _write_artifacts(output_dir: Path, report: object) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    report_dict = report.to_dict()  # type: ignore[attr-defined]

    (output_dir / "api_contract_inventory.json").write_text(
        json.dumps(report_dict, indent=2), encoding="utf-8"
    )

    # Markdown summary
    lines = [
        "# API Contract Report",
        "",
        f"**Project:** {report.project_id}",  # type: ignore[attr-defined]
        f"**Source:** `{report.source_file}`",  # type: ignore[attr-defined]
        f"**Format:** {report.source_format}",  # type: ignore[attr-defined]
        f"**Title:** {report.spec_title}",  # type: ignore[attr-defined]
        f"**Base URL:** {report.base_url}",  # type: ignore[attr-defined]
        "",
        "## Endpoint Summary",
        "",
        f"- Total endpoints: **{report.total_endpoints}**",  # type: ignore[attr-defined]
        f"- Safe (read-only): **{report.safe_readonly_count}**",  # type: ignore[attr-defined]
        f"- Requires approval: **{report.requires_approval_count}**",  # type: ignore[attr-defined]
        f"- Blocked by default: **{report.blocked_count}**",  # type: ignore[attr-defined]
        "",
        "## Endpoints",
        "",
    ]
    for ep in report.endpoints:  # type: ignore[attr-defined]
        lines.append(
            f"| `{ep.method}` | `{ep.path}` | {ep.safety_classification} | {ep.safety_reason} |"
        )

    lines += [
        "",
        "## Safety Invariants",
        "",
        f"- `raw_secrets_allowed`: {report.raw_secrets_allowed}",  # type: ignore[attr-defined]
        f"- `destructive_api_calls_allowed`: {report.destructive_api_calls_allowed}",  # type: ignore[attr-defined]
        f"- `human_review_required`: {report.human_review_required}",  # type: ignore[attr-defined]
        "",
        "_Generated by AI QA Factory Phase 5M._",
    ]
    (output_dir / "api_contract_summary.md").write_text("\n".join(lines), encoding="utf-8")

    # Auth requirements map
    auth_map = [a.to_dict() for a in report.auth_requirements]  # type: ignore[attr-defined]
    (output_dir / "auth_requirements_map.json").write_text(
        json.dumps(auth_map, indent=2), encoding="utf-8"
    )

    # Risky endpoints list
    risky = [
        e.to_dict()
        for e in report.endpoints  # type: ignore[attr-defined]
        if e.safety_classification in ("requires_approval", "blocked_by_default")
    ]
    (output_dir / "risky_endpoints.json").write_text(
        json.dumps(risky, indent=2), encoding="utf-8"
    )


def main(argv: list[str] | None = None) -> int:
    _check_blocked_flags(argv if argv is not None else sys.argv[1:])

    parser = argparse.ArgumentParser(
        description="Import and classify an API contract (OpenAPI/Postman)."
    )
    parser.add_argument("--project-id", required=True, help="Project identifier")
    parser.add_argument("--spec-file", required=True, help="Path to OpenAPI JSON/YAML or Postman collection")
    parser.add_argument("--outputs-root", default="outputs", help="Root outputs directory")
    parser.add_argument("--no-write", action="store_true", help="Skip writing artifacts")

    args = parser.parse_args(argv)

    spec_path = Path(args.spec_file)
    if not spec_path.exists():
        print(f"[ERROR] Spec file not found: {spec_path}", file=sys.stderr)
        return 1

    from core.api_contract_importer import APIContractImporter
    importer = APIContractImporter()
    report = importer.analyze(args.project_id, str(spec_path))

    if report.parse_errors:
        for err in report.parse_errors:
            print(f"[WARN] {err}")

    print(f"[OK] Parsed {report.total_endpoints} endpoints from {report.source_format}")
    print(f"     Safe: {report.safe_readonly_count} | Approval: {report.requires_approval_count} | Blocked: {report.blocked_count}")

    if not args.no_write:
        output_dir = Path(args.outputs_root) / args.project_id / _ARTIFACT_DIR
        _write_artifacts(output_dir, report)
        print(f"[OK] Artifacts written to {output_dir}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
